# Introdução {#sec-introducao}

A Jurimetria é um ramo do Direito ainda em definição. Não se sabe ao certo a que métodos e técnicas se refere a Jurimetria, tampouco como a própria Jurimetria concebe o seu objeto de estudo, isto é, o Direito. Em outras palavras, a Jurimetria não é dotada de metodologia e epistemologia próprias, de forma que não é possível (ainda) distinguir completamente a Jurimetria da Análise Econômica do Direito, ou de outros estudos que tratem quantitativamente do Direito, tal como as Ciências Políticas podem fazer, ou como a própria Estatística o faz. Hoje em dia, a Jurimetria é definida pelas aplicações existentes.

Ainda assim é possível traçar algumas considerações sobre do que se trata a Jurimetria. A definição mais precisa que temos atualmente é a de Marcelo Guedes Nunes, que a define como uma (a) disciplina do conhecimento que (b) utiliza a metodologia estatística para (c) investigar o funcionamento de uma ordem jurídica^[@Nunes2016]. Essa definição contém três elementos: (a) a taxonomia da jurimetria, (b) o seu método e (c) objeto.

Sobre a taxonomia, é importante frisar dessa definição a Jurimetria enquanto uma "disciplina do conhecimento", porque é muito comum encontrar uma redução dessa área do conhecimento a somente o seu método. Ou seja, é frequente a definição da Jurimetria como somente "a aplicação de métodos estatísticos ao Direito". Mas uma área do conhecimento envolve muito mais do que somente o seu método. Uma área do conhecimento implica uma forma de se conhecer o seu objeto de estudo própria. Então é disso que se trata a Jurimetria: sobre uma forma de conhecer e conceber o Direito. 

Sobre o método, talvez esse seja o elemento mais claro da Jurimetria, ele é, de forma genérica, a aplicação de métodos estatísticos ao Direito. Isso significa que a Jurimetria incorpora os métodos e técnicas quantitativos no estudo do Direito. Entretanto é importante salientar que por "métodos e técnicas quantitativos" não estamos nos referindo a um único sistema homogêneo de métodos e de técnicas. Existem uma infinidade de discussões metodológicas e de divergências teóricas dentro da própria Estatística, como os debates sobre estatística frequentista e bayesiana. A Jurimetria não se posiciona de nenhum lado das discussões da Estatística; ela não designa nenhum método ou técnica em específico dentro da Estatística. A Jurimetria apenas significa a aplicação destes métodos, em suas mais variadas formas, em todas as suas vertentes.

Sobre este ponto, inclusive, é importante fazermos uma ressalva a respeito deste livro, porque, por mais que a Jurimetria enquanto área do conhecimento não se posicione em nenhuma discussão da Estatística, preferindo ou preterindo um ou outro método, não vamos abordar essas divergências, tampouco abordaremos todas as ramificações e abordagens possíveis dentro da Estatística. Em outras palavras, mesmo que a Jurimetria não se designe métodos e técnicas específicas, este livro irá abordar apenas algumas dessas técnicas, realizando, portanto, escolhas do que falar e do que não falar. Mas nada disso significa que os métodos e técnicas difundidos por este livro sejam exaustivos de todo o ramo da Jurimetria. Aqui, falaremos dos métodos e técnicas que a Associação Brasileira de Jurimetria mais comumente utiliza em suas pesquisas. 

Por fim, a respeito do objeto, a Jurimetria se propõe a discutir "o funcionamento da ordem jurídica". São duas palavras importantes a respeito desse objeto: "funcionamento" e "ordem jurídica". A começar pela ordem jurídica, este conceito é muito amplo e genérico. O que importa salientar a seu respeito é que por "ordem jurídica" nos referimos a um objeto maior do que simplesmente o conjunto de normas que compõem algum ordenamento jurídico. Além das normas, existem as suas interpretações, métodos de hermenêutica, as discussões doutrinárias e jurisprudenciais. Mas a Jurimetria não se delimita somente por estudar a "ordem jurídica". Mais do que isso, ela estuda o "funcionamento" dessa ordem. Isso significa que o que se estuda são, não as normas em abstrato, não a ordem jurídica no plano normativo, mas a ordem jurídica no seu plano concreto, factual, com especial atenção para a atuação dos tribunais, dos operadores do Direito e da Administração Pública. 

Feita uma definição sobre a Jurimetria, é importante tratarmos de algumas notas epistemológicas sobre a forma (métodos quantitativos) como a Jurimetria conhece o seu objeto de estudo (o funcionamento da ordem jurídica). Tratar desses problemas é uma forma de alerta para os limites inerentes à Jurimetria, e também, possivelmente, uma forma de se preparar para as críticas a que estão sujeitos os trabalhos e estudos nessa área. Trataremos de dois problemas. O primeiro diz respeito a um problema geral de toda a pesquisa empírica do Direito (seja quantitativa, seja qualitativa); o segundo diz respeito a um problema geral de toda a pesquisa quantitativa (seja no Direito, ou fora dele). A Jurimetria é um ramo único pois é a única área do conhecimento que concentra esses dois problemas em um único lugar. 

O primeiro problema epistemológico (o problema geral de pesquisa empírica no Direito) diz respeito à natureza das proposições que podemos fazer sobre o Direito. O Direito trata de afirmações *normativas* sobre o mundo, enquanto toda pesquisa empírica no Direito realiza afirmações *descritivas.* Dessa forma, surge uma questão que José Xavier coloca muito bem: as pesquisas empíricas cujo o objeto é o Direito são pesquisas **em** Direito, ou pesquisas **com** o Direito ou **sobre** o Direito?^[A citação é na verdade: "Se concebermos o direito como o mundo da doutrina, o mundo da elaboração teórica de categorias para a tomada de decisão, qual espaço resta para a pesquisa empírica **em** direito? Em outras palavras, para que a pesquisa empírica seja em direito, e não apenas **com** ou **sobre** o direito, é preciso ter uma concepção do direito que compreenda que o direito é aquilo que pode ser observado para além de construções doutrinárias e normas positivadas." @Xavier2015] Essa pergunta é importante, porque ela coloca uma questão epistemológica essencial: seriam as pesquisas empíricas no Direito pesquisas feitas a partir do ponto de vista interno ou externo do Direito? É possível uma pesquisa empírica em Direito, isto é, assumindo o seu ponto de vista interno? Essa pergunta indica que ainda está em debate se a Jurimetria pode realmente apresentar um ponto de vista interno ao Direito, ou se, por natureza, ela está condenada a apresentar sempre um ponto de vista externo?

Sobre o segundo problema (o problema geral de métodos quantitativos), é importante começarmos a delimitá-lo dizendo que todos os ramos das ciências sociais – e é importante aqui frisar que estamos falando das ciências sociais, e não das ciências naturais – buscam, de uma forma ou de outra, apreender a realidade social, dar sentido a ela, mas cada uma das diferentes áreas das ciências sociais possui um conceito de verdade distinto. Dessa forma, por mais que vários ramos das ciências humanas olhem para um mesmo objeto (como o Direito, por exemplo), elas vão olhar para ele a partir de lentes distintas e chegar a conclusões distintas. Essas lentes são essenciais porque em certo grau elas determinam o tipo de conclusão que se pode tirar a respeito desse objeto. Disso então decorre uma pergunta importante: que tipos de perguntas e de conclusões podemos tirar a respeito do Direito quando olhamos para ele a partir de dados, aplicando métodos quantitativos? E o que não podemos enxergar dessa forma? 

Este livro não vai se debruçar sobre essas duas questões mais profundamente, mas são questões que devem ficar na cabeça de quem lê sempre que ela for aplicar as técnicas aprendidas aqui. 

Estes eram os pontos iniciais importantes de serem tratados antes que nos iniciássemos no método e nas técnicas quantitativas. O que o livro se propõe a fazer de agora em diante é descrever as técnicas empregadas para fazer análises quantitativas.
