# tjmg_santos_dumont ------------------------------------------------------

# 2ª Vara Cível, Criminal e de Execuções Penais da Comarca de Santos Dumont, Estado de Minas Gerais

# https://portal14b.com.br/Publicacao.aspx?id=348233

juri <- tibble::tibble(
  id = 1:159,
  nome = c(
    "Adalberto Marino Martins Alves",
    "Adline Lopes",
    "Adriana da Conceição Ferreira Martins Alves",
    "Alessandra Marques de Mello",
    "Alessandra Pires Pulhiese",
    "Alexandre Aparecido da Silva Rosa",
    "Aline Roberta de Souza",
    "Amanda Machado Dias",
    "Ana Luiza Mansur Albanese",
    "Ana Clara da Silva Marques",
    "Anderson Meirelles Janiques",
    "André Luiz Faria Valle",
    "Andreia Eliza Freire Venâncio",
    "Andressa Juliane de Amorim Netto",
    "Anisberta Reis de Souza",
    "Augusto Cesar Silva de Carvalho",
    "Barbara Vieira Marques Moreira Barros",
    "Bruna Alves Novaes",
    "Bruna de Paula da Silva",
    "Bruna Martins da Silva",
    "Bruna Rodrigues Santos Pereira",
    "Bruno Majeste Silva",
    "Camila Cristina de Amaral",
    "Carla Helena Villela de Castro",
    "Carla Ribeiro de Almeida Vitorelli",
    "Carlos José de Assis Pereira",
    "Carlos Magno Saraiva",
    "Carmelia de Castro Vargas",
    "Carmelita Marques de Amorim",
    "Carolina de Paiva Cunha",
    "Carolinni Maria Dias da Costa",
    "Cassiel Francisco de Azevedo",
    "Catiusca Mara dos Santos",
    "Celia Regina Pires Ramos",
    "Chaieni Moreira Ribeiro",
    "Cintia Cristina Ferreira",
    "Cinthya dos Santos Martins Araújo",
    "Cláudia Mansur",
    "Conrado Luciano Baptista",
    "Cristiane Helena de Almeida",
    "Daniel Baptista Lopes da Silva",
    "Daniele Cristina Venancio",
    "Danilo José Marques",
    "Davi Antônio da Fonseca Vieira",
    "Deborah Fernanda Medeiros de Mendonça",
    "Diogo Quintino Ferreira de Almeida",
    "Diva Odilia da Silva",
    "Edgar Gilberto do Nascimento",
    "Eduardo de Souza Castro",
    "Edna Fátima Pereira",
    "Elisangela Aparecida Pereira Nogueira",
    "Elizangela Aparecida de Paula Gomes Alves",
    "Elizangela Maria dos Santos Mendes",
    "Elizene Esteves",
    "Eunice Olinda Cunha",
    "Fabricio Jorge Oliveira",
    "Felipe da Silva Chaves",
    "Fernando Antônio Correa de Sá",
    "Flávia Carreira Vital da Silva",
    "Flávia Cristina Pereira Ferreira",
    "Flávio Abdallah Mendes",
    "Flávio Oliveira Nascimento",
    "Francisco Carlos Pereira",
    "Francisco de Araújo Ribeiro",
    "Frederico Amorim Germano",
    "Gabriela de Oliveira Ruffo Lima",
    "Gustavo Antony Gomes",
    "Gustavo Lucas da Silva",
    "Hélio Cardoso Júnior",
    "Hellen Martins Barbosa",
    "Henrique do Nascimento Volpe",
    "Jairo de Castro Nascimento",
    "Jansen Nepomuceno de Paula",
    "Janaina Alvim Mendes",
    "Janaina Ferreira de Souza",
    "Janine Nara de Figueiredo",
    "Jéssica Faria Machado",
    "Jhonattan Felipe de Oliveira Serafim",
    "John Lenon Ferreira",
    "Jorge Luiz Silva das Graças",
    "José Ricardo de Oliveira",
    "Josiane de Oliveira Fernandes",
    "Juliana Chaves Costa",
    "Juliana Wemeck Barros",
    "Juliano Amaral Ferreira Toledo",
    "Kauã William da Silva Oliveira",
    "Karoline Monteiro de Lima",
    "keila Dornelas de Araújo Vitorino",
    "Kênia Rotatori Teixeira",
    "Laides Aparecida de Oliveira Xavier",
    "Larissa Christina Barbosa de Souza Salgado",
    "Leandro José de Paula",
    "Lenice Mendonça dos Santos",
    "Leonardo Castro de Souza",
    "Letícia Aparecida de Almeida",
    "Lívia Mendes Barbosa",
    "Liziane da Silva Santiago",
    "Lorena Campos de Andrade",
    "Luana Queiroz Pinheiro Carvalho",
    "Luciane Cristina Ferreira da Silva",
    "Luciano Gomes",
    "Luiz Cláudio Ribeiro da Silva",
    "Luiz Fernando da Silva",
    "Luiz Fernando de Mendonça",
    "Luzia Aparecida de Amorim Victor",
    "Maicon Calixto Toledo de Castro",
    "Marcele Albuquerque Souza Gonçalves",
    "Marcele Cristina Esperança Maciel",
    "Marcia Helena Fontes Ribeiro",
    "Marcos Valério Nepomuceno",
    "Marcelo José de Almeida Santos",
    "Maria Aparecida Grillo",
    "Maria Cristina Garcia Lima",
    "Maria Eduarda dos Santos Monteiro",
    "Mariana de Almeida Botelho",
    "Miguel Ambrozio da Silva",
    "Milena Cristina da Silva",
    "Nathália Pereira dos Santos Araújo",
    "Nicole Costa Palmieri",
    "Oscar da Silva Lopes",
    "Patricia Ferreira Vilella",
    "Pedro Henrique de Paula Morais",
    "Pierre de Castro Oliveira Bento",
    "Priscila Abijaude Alonso",
    "Priscila de Castro Novaes",
    "Puebla Oliveira Alves Alvim",
    "Rafael Martins Rodrigues",
    "Rahesley Ferreira Vigilato",
    "Raquel Maria de Oliveira",
    "Ricardo Alberto de Souza Paiva",
    "Richard Celestino",
    "Roberta Maria Caldeira Brant Neves",
    "Rodrigo Pereira Campos",
    "Rosana Aparecida dos Santos Silva Neves",
    "Rosemeyre Marques",
    "Samanta Gerolivia Honorato",
    "Sara  Maria Neves da Silva",
    "Sarah Rayla Cabral",
    "Saulo Mauricio Tavares Mendes",
    "Sebastião Vieira da Silva Neto",
    "Sérgio Antônio de Mello",
    "Siomara Dias Pinheiro",
    "Steffany Marinho Barbosa",
    "Tadeu Ferreira Lima",
    "Tamires Campos Borges Martins",
    "Tânia Aparecida Cecílio",
    "Tatiana Helena Avelino Ferreira Amorim",
    "Tercio Lucio Ferreira",
    "Thiago Nascimento Parada",
    "Tonia Mara Cândido",
    "Vanderson Martins Dorneles",
    "Vitória Neto de Araújo",
    "Vitória Regina da Silva",
    "Viviana Carolina da Silva",
    "Wendel Eduardo do Amaral",
    "Wellington Batista Bastos",
    "Weverson Ronaldo de Souza",
    "Yarla Marilia de Oliveira e Silva",
    "Yasmin Fortes Nunes"
  ),
  profissoes = c(
    "Professor",
    "Esteticista",
    "Professora",
    "Professora",
    "Professora",
    "Servidor Público Municipal",
    "Do Lar",
    "Professora",
    "Nutricionista",
    "Estudante",
    "Técnico de Enfermagem",
    "Estudante",
    "Do lar",
    "Consultora",
    "Pedagoga",
    "Professor",
    "Supervisora Escolar Municipal",
    "Professora",
    "Do Lar",
    "Psicóloga",
    "Professora",
    "Bacharel em Direito",
    "Estudante",
    "Auxiliar Cartorário",
    "Professora",
    "Estudante de Direito",
    "Bancário",
    "Professora",
    "Estudante",
    "Funcionária Pública",
    "Professora de Ensino Médio",
    "Estudante",
    "Professora de Educação Especial",
    "Agente de Saúde",
    "Educador Físico",
    "Professora",
    "Bancária",
    "Professora",
    "Advogado",
    "Professora",
    "Estudante",
    "Cabeleireira",
    "Bancário",
    "Médico",
    "Professora",
    "Dentista",
    "Professora",
    "Auxiliar de logística",
    "Estudante",
    "Professora",
    "Atendente de Padaria",
    "Professora",
    "Estudante",
    "Empresária",
    "Professora",
    "Ferroviário Aposentado",
    "Vereador",
    "Empresário",
    "Pedagoga",
    "Professora",
    "Empresário",
    "Empresário",
    "Vigilante",
    "Professor",
    "Empresário",
    "Advogada",
    "Estudante",
    "Músico",
    "Advogado",
    "Farmacêutica",
    "Empresário",
    "Advogado",
    "Advogado",
    "Professora",
    "Técnico em Patologia Clínica",
    "Recepcionista",
    "Estudante",
    "Educador Físico",
    "Advogado",
    "Técnico em Enfermagem",
    "Técnico em Operações",
    "Professora",
    "Médica",
    "Professora",
    "Estudante",
    "Estudante",
    "Empresária",
    "Estudante",
    "Advogada",
    "Advogada",
    "Educadora Física",
    "Supervisor de Manutenção e Professor",
    "Auxiliar Administrativo II",
    "Porteiro",
    "Estudante",
    "Estudante",
    "Cuidadora de Idoso",
    "Biomédica",
    "Analista Financeiro",
    "Auxiliar de Serviços Gerais",
    "Vereador",
    "Metalúrgico",
    "Logista",
    "Advogado",
    "Professora",
    "Advogado",
    "Estudante",
    "Funcionária Pública",
    "Auxiliar de Secretaria",
    "Funcionário Público Municipal",
    "Eletricista",
    "Jornalista",
    "Pedagoga",
    "Estudante de Direito",
    "Advogada",
    "Bancário",
    "Representante de Atendimento",
    "Professora",
    "Estudante",
    "Servidor Público Municipal",
    "Professora",
    "Advogado",
    "Estudante",
    "Dentista",
    "Advogada",
    "Professora",
    "Técnico em Mecânica",
    "Advogada",
    "Servente de limpeza",
    "Servidor Público Municipal",
    "Funcionário Público Federal",
    "Professora",
    "Ferroviário",
    "Agente de Saúde",
    "Funcionária Pública Municipal",
    "Auxiliar de Escritório",
    "Estudante",
    "Advogada",
    "Administrador",
    "Estudante",
    "Serventuário de Justiça",
    "Empresária",
    "Estudante",
    "Educador Físico",
    "Bacharel em Direito",
    "Farmacêutica",
    "Auxiliar de Escritório",
    "Metalúrgico",
    "Estudante",
    "Auxiliar de Cartório",
    "Ferroviário",
    "Estudante",
    "Estudante",
    "Bacharel em Direito",
    "Estudante",
    "Educador Físico",
    "Ferroviário",
    "Enfermeira",
    "Estudante"
  )
)

juri |>
  dplyr::count(profissoes) |>
  dplyr::arrange(desc(n))



# jfsp_sp -----------------------------------------------------------------

# install.packages("textreadr")


# tjpr_curitiba -----------------------------------------------------------

# https://www.tjpr.jus.br/lista-de-jurados/-/asset_publisher/M4kc/content/lista-definitiva-de-jurados-2023/163849?inheritRedirect=false&redirect=https%3A%2F%2Fwww.tjpr.jus.br%2Flista-de-jurados%3Fp_p_id%3D101_INSTANCE_M4kc%26p_p_lifecycle%3D0%26p_p_state%3Dnormal%26p_p_mode%3Dview%26p_p_col_id%3Dcolumn-4%26p_p_col_count%3D1
