<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="Livro sobre metodologia de pesquisa jurimétrica escrito pela Associação Brasileira de Jurimetria (ABJ) para ser utilizado em cursos de Jurimetria para pessoas do Direito.">
<title>Metodologia de Pesquisa Jurimétrica - 4&nbsp; Visualização</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05-modelagem.html" rel="next">
<link href="./03-estatisticas.html" rel="prev">
<link href="./assets/img/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar"
  }
}</script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
<meta property="og:title" content="Metodologia de Pesquisa Jurimétrica - 4&nbsp; Visualização">
<meta property="og:description" content="Livro sobre metodologia de pesquisa jurimétrica escrito pela
Associação Brasileira de Jurimetria (ABJ) para ser utilizado em cursos
de Jurimetria para pessoas do Direito.">
<meta property="og:image" content="https://livro.abj.org.br/assets/img/abj_inside.png">
<meta property="og:site-name" content="Metodologia de Pesquisa Jurimétrica">
<meta name="twitter:title" content="Metodologia de Pesquisa Jurimétrica - 4&nbsp; Visualização">
<meta name="twitter:description" content="Livro sobre metodologia de pesquisa jurimétrica escrito pela
Associação Brasileira de Jurimetria (ABJ) para ser utilizado em cursos
de Jurimetria para pessoas do Direito.">
<meta name="twitter:image" content="https://livro.abj.org.br/assets/img/abj.png">
<meta name="twitter:creator" content="abjurimetria">
<meta name="twitter:card" content="summary_large_image">
</head>
<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg navbar-dark "><div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./assets/img/logo.png" alt="" class="navbar-logo"></a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
<li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/abjurimetria"><i class="bi bi-twitter" role="img" aria-label="Twitter">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/abjur/livro"><i class="bi bi-github" role="img" aria-label="Source Code">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="./livro_jurimetria.pdf"><i class="bi bi-file-pdf" role="img" aria-label="Download PDF">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item dropdown  compact">
    <a class="nav-link dropdown-toggle" href="#" id="" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-share" role="img" aria-label="Share">
</i> 
 <span class="menu-text"></span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="">
<li>
    <a class="dropdown-item" href="https://twitter.com/intent/tweet?url=%7Curl%7C"><i class="bi bi-twitter" role="img">
</i> 
 <span class="dropdown-text">Twitter</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.linkedin.com/sharing/share-offsite/?url=%7Curl%7C"><i class="bi bi-linkedin" role="img">
</i> 
 <span class="dropdown-text">LinkedIn</span></a>
  </li>  
    </ul>
</li>
</ul>
<div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Visualização</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Boas vindas!</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introdução</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-planejamento.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Planejamento de Pesquisa</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-estatisticas.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Estatísticas</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-visualizacao.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Visualização</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-modelagem.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modelagem</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-refs.html" class="sidebar-item-text sidebar-link">Bibliografia</a>
  </div>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Índice</h2>
   
  <ul>
<li>
<a href="#para-que-servem-visualiza%C3%A7%C3%B5es" id="toc-para-que-servem-visualizações" class="nav-link active" data-scroll-target="#para-que-servem-visualiza%C3%A7%C3%B5es"><span class="toc-section-number">4.1</span>  Para que servem visualizações?</a>
  <ul class="collapse">
<li><a href="#detetive-de-dados---an%C3%A1lise-explorat%C3%B3ria-de-dados" id="toc-detetive-de-dados---análise-exploratória-de-dados" class="nav-link" data-scroll-target="#detetive-de-dados---an%C3%A1lise-explorat%C3%B3ria-de-dados"><span class="toc-section-number">4.1.1</span>  Detetive de dados - Análise exploratória de dados</a></li>
  </ul>
</li>
  <li><a href="#comunicadora-de-dados---apresenta%C3%A7%C3%A3o-de-dados" id="toc-comunicadora-de-dados---apresentação-de-dados" class="nav-link" data-scroll-target="#comunicadora-de-dados---apresenta%C3%A7%C3%A3o-de-dados"><span class="toc-section-number">4.2</span>  Comunicadora de dados - Apresentação de dados</a></li>
  <li>
<a href="#visualiza%C3%A7%C3%B5es-em-esp%C3%A9cie" id="toc-visualizações-em-espécie" class="nav-link" data-scroll-target="#visualiza%C3%A7%C3%B5es-em-esp%C3%A9cie"><span class="toc-section-number">4.3</span>  Visualizações em espécie</a>
  <ul class="collapse">
<li><a href="#visualiza%C3%A7%C3%B5es-de-vari%C3%A1veis-categ%C3%B3ricas" id="toc-visualizações-de-variáveis-categóricas" class="nav-link" data-scroll-target="#visualiza%C3%A7%C3%B5es-de-vari%C3%A1veis-categ%C3%B3ricas"><span class="toc-section-number">4.3.1</span>  Visualizações de variáveis categóricas</a></li>
  <li><a href="#visualiza%C3%A7%C3%B5es-de-vari%C3%A1veis-quantitativas" id="toc-visualizações-de-variáveis-quantitativas" class="nav-link" data-scroll-target="#visualiza%C3%A7%C3%B5es-de-vari%C3%A1veis-quantitativas"><span class="toc-section-number">4.3.2</span>  Visualizações de variáveis quantitativas</a></li>
  </ul>
</li>
  </ul><div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/abjur/livro/edit/main/04-visualizacao.qmd" class="toc-action">Editar essa página</a></p><p><a href="https://github.com/abjur/livro/issues/new" class="toc-action">Criar uma issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-visualizacao" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Visualização</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><p>No <a href="02-planejamento.html">Capítulo&nbsp;<span>2</span></a>, nós vimos questões sobre o método quantitativo, já no <a href="03-estatisticas.html">Capítulo&nbsp;<span>3</span></a>, passamos do método às medidas. Nesta ocasião, vimos as medidas de duas formas diferentes: as medidas das observações consideradas individualmente e as medidas de resumo do conjunto de observações. Na parte das medidas individuais de cada observação, vimos que as características das observações podem ter duas naturezas distintas, ou elas são categóricas (pois indicam uma categoria de resposta), ou elas são quantitativas (pois indicam uma resposta numérica). Essas duas naturezas possíveis possuem suas subdivisões, mas o mais importante é considerarmos essas duas grandes classes. Em seguida, na parte de medidas resumo do conjunto das observações, tivemos que separar as medidas resumo das variáveis categóricas das medidas resumo das variáveis quantitativas.</p>
<p>Neste capítulo, ainda vamos nos valer desta distinção – entre variáveis categóricas e numéricas –, mas não vamos falar de medidas de resumo. O foco deste capítulo são as visualizações relacionadas a cada tipo de dado. Inicialmente, precisamos discutir para que servem as visualizações suas vantagens e desvantagens. Em seguida, vamos falar das visualizações específicas de cada tipo de variável (categórica ou quantitativa), começando pelas visualizações das variáveis categóricas para seguir então para as visualizações das variáveis quantitativas. Depois de olhar como representar individualmente as variáveis, vamos olhar para gráficos bivariados.</p>
<section id="para-que-servem-visualizações" class="level2" data-number="4.1"><h2 data-number="4.1" class="anchored" data-anchor-id="para-que-servem-visualizações">
<span class="header-section-number">4.1</span> Para que servem visualizações?</h2>
<p>Hoje em dia, nós vemos gráficos em vários contextos da vida cotidiana. Vemos gráficos em jornais, apresentações, livros, artigos de revista e em um monte de outros lugares. Mas nem sempre foi assim. Tratar de <em>dados</em> por meio de <em>visualizações gráficas</em> é apenas um jeito de contar a história. No capítulo anterior, vimos como contar a história, não por meio de gráficos, mas por meio de medidas de resumo. Se os gráficos nem sempre foram utilizados, cabe nos perguntarmos por que eles ganharam essa relevância nos dias atuais? O que eles trazem que outras formas de comunicar as informações (como em tabelas) não trazem?</p>
<p>Vamos começar essa discussão com uma citação importante, retirada do livro The <em>Elements of Graphing Data</em> [Os Elementos da Representação Gráfica dos Dados] (1985) do William S. Cleveland. Na sessão <em>the power of graphical display</em> [o poder da representação gráfica], Cleveland diz:</p>
<blockquote class="blockquote">
<p>Representações gráficas são uma ferramenta excepcional para a análise de dados. A razão disso está bem resumida em uma sentença de uma carta de 1982 escrita pelo senhor W. Edwards Deming a mim: “Os métodos gráficos podem reter a informação nos dados”. Procedimentos numéricos de análise de dados – tais como a média, o desvio padrão, coeficientes de correlação e teste-t – são essencialmente técnicas de redução dos dados. Os métodos gráficos complementam essas técnicas. Os métodos gráficos tendem a mostrar conjuntos de dados como um todo, permitindo-nos resumir o comportamento geral e estudar o detalhe. Isso nos leva a uma análise de dados mais minuciosa. Uma razão para as representações gráficas conseguirem reter as informações dos dados é que uma grande quantidade de informação quantitativa pode ser exibida e absorvida<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
</blockquote>
<p>Para dar um exemplo do que significa conseguir “exibir e absorver” informações quantitativas, e para explicar também o que significa “técnicas de redução de dados”, vamos olhar para um exemplo, no qual nós comparamos três formas de apresentar os mesmos dados. Os dados expostos dizem respeito aos valores das causas de ações de consumo.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-dados-consumo" class="anchored">
<table class="table table-sm table-striped">
<caption>Tabela&nbsp;4.1: Tabela com dados de valores</caption>
<thead><tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: right;"></th>
<th style="text-align: right;">valor</th>
<th style="text-align: right;"></th>
<th style="text-align: right;"></th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">3373.20</td>
<td style="text-align: right;">29940.00</td>
<td style="text-align: right;">10000.00</td>
<td style="text-align: right;">12500.00</td>
<td style="text-align: right;">20000.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">5000.00</td>
<td style="text-align: right;">2546.50</td>
<td style="text-align: right;">1200.00</td>
<td style="text-align: right;">15000.00</td>
<td style="text-align: right;">52250.00</td>
</tr>
<tr class="odd">
<td style="text-align: right;">43873.64</td>
<td style="text-align: right;">15665.01</td>
<td style="text-align: right;">16294.08</td>
<td style="text-align: right;">11794.29</td>
<td style="text-align: right;">5843.75</td>
</tr>
<tr class="even">
<td style="text-align: right;">4224.50</td>
<td style="text-align: right;">10000.00</td>
<td style="text-align: right;">463.31</td>
<td style="text-align: right;">15000.00</td>
<td style="text-align: right;">10000.00</td>
</tr>
<tr class="odd">
<td style="text-align: right;">52900.00</td>
<td style="text-align: right;">6125.96</td>
<td style="text-align: right;">9449.46</td>
<td style="text-align: right;">6299.77</td>
<td style="text-align: right;">54880.14</td>
</tr>
<tr class="even">
<td style="text-align: right;">4241.39</td>
<td style="text-align: right;">17293.00</td>
<td style="text-align: right;">18710.00</td>
<td style="text-align: right;">26664.00</td>
<td style="text-align: right;">8299.46</td>
</tr>
<tr class="odd">
<td style="text-align: right;">8594.40</td>
<td style="text-align: right;">5158.70</td>
<td style="text-align: right;">10000.00</td>
<td style="text-align: right;">23390.00</td>
<td style="text-align: right;">11067.60</td>
</tr>
<tr class="even">
<td style="text-align: right;">17407.35</td>
<td style="text-align: right;">15000.00</td>
<td style="text-align: right;">21650.34</td>
<td style="text-align: right;">4408.35</td>
<td style="text-align: right;">3612.00</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9980.00</td>
<td style="text-align: right;">10450.00</td>
<td style="text-align: right;">30000.00</td>
<td style="text-align: right;">10925.93</td>
<td style="text-align: right;">1000.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">95735.92</td>
<td style="text-align: right;">31236.32</td>
<td style="text-align: right;">16050.00</td>
<td style="text-align: right;">39073.68</td>
<td style="text-align: right;">10000.00</td>
</tr>
<tr class="odd">
<td style="text-align: right;">13179.28</td>
<td style="text-align: right;">23082.44</td>
<td style="text-align: right;">13180.95</td>
<td style="text-align: right;">5000.00</td>
<td style="text-align: right;">17681.82</td>
</tr>
<tr class="even">
<td style="text-align: right;">3677.88</td>
<td style="text-align: right;">1000.00</td>
<td style="text-align: right;">19224.00</td>
<td style="text-align: right;">52582.70</td>
<td style="text-align: right;">12105.00</td>
</tr>
<tr class="odd">
<td style="text-align: right;">15000.00</td>
<td style="text-align: right;">23289.31</td>
<td style="text-align: right;">1180.00</td>
<td style="text-align: right;">20000.00</td>
<td style="text-align: right;">26802.24</td>
</tr>
<tr class="even">
<td style="text-align: right;">9980.00</td>
<td style="text-align: right;">6028.00</td>
<td style="text-align: right;">134311.00</td>
<td style="text-align: right;">2003.40</td>
<td style="text-align: right;">9730.00</td>
</tr>
<tr class="odd">
<td style="text-align: right;">20000.00</td>
<td style="text-align: right;">1617.07</td>
<td style="text-align: right;">40000.00</td>
<td style="text-align: right;">6810.80</td>
<td style="text-align: right;">31462.73</td>
</tr>
<tr class="even">
<td style="text-align: right;">15144.08</td>
<td style="text-align: right;">16297.08</td>
<td style="text-align: right;">21236.52</td>
<td style="text-align: right;">2763.90</td>
<td style="text-align: right;">5450.00</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10000.00</td>
<td style="text-align: right;">4036.91</td>
<td style="text-align: right;">20000.00</td>
<td style="text-align: right;">49964.81</td>
<td style="text-align: right;">12343.62</td>
</tr>
<tr class="even">
<td style="text-align: right;">15000.00</td>
<td style="text-align: right;">13454.08</td>
<td style="text-align: right;">2944.42</td>
<td style="text-align: right;">990.51</td>
<td style="text-align: right;">2581.76</td>
</tr>
<tr class="odd">
<td style="text-align: right;">22267.55</td>
<td style="text-align: right;">13778.04</td>
<td style="text-align: right;">1000.00</td>
<td style="text-align: right;">6533.40</td>
<td style="text-align: right;">20531.12</td>
</tr>
<tr class="even">
<td style="text-align: right;">8784.00</td>
<td style="text-align: right;">17284.38</td>
<td style="text-align: right;">84523.57</td>
<td style="text-align: right;">10000.00</td>
<td style="text-align: right;">15000.00</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-medidas-resumo" class="anchored">
<table class="table table-sm table-striped">
<caption>Tabela&nbsp;4.2: Medidas de resumo</caption>
<thead><tr class="header">
<th style="text-align: left;">medidas</th>
<th style="text-align: right;">valores</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">média</td>
<td style="text-align: right;">7654.10</td>
</tr>
<tr class="even">
<td style="text-align: left;">desvio padrão</td>
<td style="text-align: right;">174.82</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mínimo</td>
<td style="text-align: right;">63.31</td>
</tr>
<tr class="even">
<td style="text-align: left;">quartil inferior</td>
<td style="text-align: right;">981.94</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mediana</td>
<td style="text-align: right;">2421.81</td>
</tr>
<tr class="even">
<td style="text-align: left;">quartil superior</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">máximo</td>
<td style="text-align: right;">34311.00</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-exemplo-vis" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-exemplo-vis-1.png" class="img-fluid figure-img" width="2400"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.1: Exemplo de visualização</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>As três apresentações de dados que fizemos foram, respectivamente, uma tabela de observações, apresentando 100 valores de causa em ações de consumo; seguido das medidas resumo dessas observações; finalizando com um histograma dessas observações. O que queremos discutir é <em>o que a apresentação gráfica nos mostra que as demais formas não nos mostram</em>?</p>
<p>A primeira apresentação dos dados nos diz muito pouco. Por mais que tenhamos uma visão de <em>todos</em> os dados, não conseguimos tirar conclusão alguma sobre eles. As informações ali estão muito cruas. É difícil de ordenar as informações e de observar tendências gerais.</p>
<p>Na segunda forma de apresentar os dados, todo aquele conjunto imenso de dados foi reduzido a algumas poucas estatísticas de resumo. No caso, escolhemos mostrar a média, o desvio padrão e algumas medidas de posição importantes (o mínimo, o máximo, os quartis inferior e superior e a mediana). Nesse caso, perdemos a noção do <em>todo</em> (pois não vemos mais cada uma das observações), para olharmos para tendências gerais. Essas medidas nos permitem olhar para algumas tendências importantes, por exemplo, conseguimos perceber que, como a média está mais à direita do que a mediana, pois R$ 7654.1 (média) é maior do que R$ 2421.81 (mediana), que a distribuição não é simétrica, mas que existem pontos à direita que estão “puxando” a média para a direito, enquanto a mediana, que é robusta como vimos, não está recebendo efeito dessas observações à direita. Confirmamos essa mesma tendência pela observação de que o desvio padrão é muito maior do que a média.</p>
<p>Todas essas conclusões que tiramos a partir das medidas resumo nos levam a perceber que a distribuição dos valores de causa de ações de consumo possui uma distribuição assimétrica para a direita (ou seja, muitos dados concentrados próximo de zero, e poucos dados muito distantes do zero). Acontece que o processo para chegarmos a essa conclusão não foi intuitivo, ele necessitou de algumas análises anteriores.</p>
<p>É com esse problema em mente que podemos olhar para o gráfico que está apresentando os mesmos dados. Duas características são importantes da representação gráfica pelo histograma: (a) o gráfico não “reduz” os dados a algumas poucas medidas, mas ele exibe todas as observações, aproximando-se, dessa forma, da primeira apresentação dos dados (isto é, a tabela de observações); (b) ao mesmo tempo em que o gráfico mostra <em>todas</em> as observações, ele ainda consegue indicar tendências gerais da distribuição dos dados, nesse sentido, aproximando-se da segunda apresentação dos dados (isto é, a tabela de medidas resumo). Aquela conclusão que tiramos a partir das medidas resumo (de que a distribuição é assimétrica para a direita, pois ela possui muitos dados concentrados próximo de zero e poucos dados distantes do zero) é reforçada no gráfico. A diferença é que conseguimos chegar a essa conclusão de uma forma muito mais intuitiva. É por essa razão que Cleveland diz que “uma grande quantidade de informação quantitativa pode ser exibida e <strong>absorvida</strong>”, com destaque para a palavra “absorvida”.</p>
<p>A partir desse exemplo, conseguimos compreender algumas características importantes das visualizações gráficas: elas conseguem manter um olhar para <em>cada uma das observações</em> (sem reduzir os dados a algumas poucas medidas), e, ao mesmo tempo, conseguem apresentar tendências gerais da distribuição dos dados de uma forma de fácil absorção e compreensão por aquele que visualiza.</p>
<p>Com essas características em mente, então, podemos prosseguir à próxima pergunta: para que servem visualizações?. Há duas respostas importantes: as visualizações gráficas servem para investigar os dados, bem como servem para comunicar resultados. Vamos olhar para as duas funções</p>
<section id="detetive-de-dados---análise-exploratória-de-dados" class="level3" data-number="4.1.1"><h3 data-number="4.1.1" class="anchored" data-anchor-id="detetive-de-dados---análise-exploratória-de-dados">
<span class="header-section-number">4.1.1</span> Detetive de dados - Análise exploratória de dados</h3>
<p>Uma forma de encarar as visualizações gráficas é criar visualizações a fim de se obter evidências e pistas para analisar outros fenômenos. Isso é o que <span class="citation" data-cites="Tukey1977">Tukey (<a href="06-refs.html#ref-Tukey1977" role="doc-biblioref">1977</a>)</span> chama de “quantitative detective work” [trabalho de detetive quantitativo]. Nesse sentido, a visualização de dados não é um fim em si mesmo, mas é uma etapa para um processo de compreensão maior. Nesse sentido, usamos visualizações gráficas para descobrir como um determinado dado se distribui; e a partir dessa informação, podemos perceber que talvez seja adequado fazer uma transformação de variável. Por exemplo, ao analisar o valor da causa, podemos nos deparar com a seguinte distribuição, conforme a <a href="#fig-hist-causa">Figura&nbsp;<span>4.2</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-hist-causa" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-hist-causa-1.png" class="img-fluid figure-img" width="2700"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.2: Distribuição do valor da causa</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Não queremos colocar um gráfico desses em um relatório, ou em um artigo a ser publicado. Mas esse gráfico é importante para percebemos que o eixo x (valor) precisa passar por um ajuste. O ajuste que vamos fazer é colocar o valor em escala logarítmica. Essa é uma transformação muito comum. Mais para frente veremos por que, quando e como fazer essa transformação, por hora, basta sabermos que o primeiro gráfico foi um indicativo de que precisávamos mudar a escala da variável <code>valor</code>. Esse gráfico conseguiu nos indicar isso pois ele nos revelou a distribuição das observações sobre essa variável. E ao saber a distribuição, conseguimos padronizar melhor os dados. Na <a href="#fig-hist-causa-log">Figura&nbsp;<span>4.3</span></a>, vemos as mesmas informações dispostas na <a href="#fig-hist-causa">Figura&nbsp;<span>4.2</span></a>, ajustadas com log.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-hist-causa-log" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-hist-causa-log-1.png" class="img-fluid figure-img" width="2700"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.3: Distribuição do valor de causa (com log);</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>A partir da <a href="#fig-hist-causa-log">Figura&nbsp;<span>4.3</span></a>, conseguimos observar uma distribuição totalmente diferente daquela expressa na <a href="#fig-hist-causa">Figura&nbsp;<span>4.2</span></a>. Essa nova figura tem alguns problemas de interpretação, por exemplo, o que significa que o valor da causa ser log 8? A informação não está equivocada, mas ela só está de difícil interpretação. O que queríamos mostrar é que a <a href="#fig-hist-causa">Figura&nbsp;<span>4.2</span></a> foi usada, não para apresentar os dados que ela continha, mas como um meio para chegarmos à <a href="#fig-hist-causa-log">Figura&nbsp;<span>4.3</span></a>.</p>
<p>São usos deste tipo que aqui estamos chamando de uma análise exploratória de dados. Nesse sentido (de exploratório), os gráficos servem de instrumento de investigação de relações. Veremos ao longo do livro várias formas de usar gráficos nesse sentido, tais como testes de normalidade, verificar pressupostos de modelos, descobrir outliers, entre muitos outros.</p>
</section></section><section id="comunicadora-de-dados---apresentação-de-dados" class="level2" data-number="4.2"><h2 data-number="4.2" class="anchored" data-anchor-id="comunicadora-de-dados---apresentação-de-dados">
<span class="header-section-number">4.2</span> Comunicadora de dados - Apresentação de dados</h2>
<p>Outra função que podemos dar à visualização de dados é a comunicação dos resultados. Bons gráficos devem ser gráficos que consigam ser facilmente compreendidos; são gráficos claros e intuitivos. Existe uma série de estudos sobre como construir gráficos para comunicação, assim como existem muitos exemplos, principalmente no jornalismo, de gráficos que contam boas histórias.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>Recomendamos aqui a leitura de Cleveland, William S. The Elements of Graphing Design. California: Wadsworth Advanced Book Program. 1985; ou para um resumo e aplicação prática de Cleveland, recomendamos Kozak, Marcin. Basic principles of graphing data. Sci. Agric. (Piracicaba, Braz.), v.67, n.4, p.483-494, July/August 2010. Neste artigo de Kozak, ele resume os princípios elencados por Cleveland em The Elements of Graphing Data, bem como fornece valiosos exemplos de como esses princípios podem melhorar a apresentação gráfica.</p>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>Aqui recomendamos os <a href="">gráficos do Nexo Jornal</a>(https://www.nexojornal.com.br/grafico/); a <a href="https://piaui.folha.uol.com.br/tag/igualdades/">sessão Igualdades da Revista Piaui</a>; os <a href="https://www.nytimes.com/spotlight/graphics">gráficos do New York Times</a>; as <a href="https://www.nucleo.jor.br/">reportagens do Núcleo de Jornalismo</a>; e, por fim, <a href="https://arte.estadao.com.br/brasil/adocao/criancas/">esta reportagem do Estadão sobre adoção de crianças</a>. Todos os sites foram acessados em 28/04/2022.</p>
</div>
</div>
<p>Temos que ter alguns cuidados nessa parte de comunicação dos resultados. A comunicação é uma etapa que, se feita de forma equivocada, pode não conseguir passar a interpretação correta dos resultados, ou ainda, se for feita de forma maliciosa, pode passar informações falsas.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ver o exemplo discutido por Cleveland, 1985, sobre o gráfico que o Carl Sagan apresentou em seu livro Os Dragões do Éden a respeito da relação entre a proporção da massa do cérebro em relação à massa do corpo e a inteligência de diversas espécies. O exemplo se encontra em na sessão 1.3. The Challenge of Graphical Display do livro Cleveland, William S. The Elements of Graphing Design. California: Wadsworth Advanced Book Program. 1985.</p>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ver o artigo de Caio Lente no blog da Curso-R, em que ele descreve como os dados podem mentir, ao se analisar uma imagem sobre o desenvolvimento econômico da Argentina após a Reforma Constitucional que ensejou o início da Justiça Social. O artigo está disponível <a href="https://blog.curso-r.com/posts/2020-01-21-fake-news/">neste link</a>, acessado em 28/04/2022.</p>
</div>
</div>
</section><section id="visualizações-em-espécie" class="level2" data-number="4.3"><h2 data-number="4.3" class="anchored" data-anchor-id="visualizações-em-espécie">
<span class="header-section-number">4.3</span> Visualizações em espécie</h2>
<p>Tendo em mente as características e funções das visualizações, podemos prosseguir ao detalhamento de algumas espécies de visualizações. Existem muitos tipos de gráficos. Você pode ver uma tentativa de documentação completa desses gráficos em <a href="https://www.data-to-viz.com/">From data to Viz</a>. Não vamos falar de todos esses gráficos, mas apenas dos tipos mais frequentes. Da mesma forma como nós dividimos a explicação das medidas de resumo entre as explicações das medidas para variáveis categóricas e as medidas para variáveis numéricas, vamos, novamente, seguir este padrão, de modo que apresentaremos:</p>
<ol type="1">
<li>Visualizações para variáveis categóricas
<ol type="1">
<li>Gráficos univariados</li>
<li>Gráficos bivariados
<ol type="1">
<li>Com explicativa categórica</li>
<li>Com explicativa numérica (só faz sentido regressão)</li>
</ol>
</li>
</ol>
</li>
<li>Visualizações para variáveis numéricas
<ol type="1">
<li>Gráficos univariados</li>
<li>Gráficos bivariados
<ol type="1">
<li>Com explicativa categórica</li>
<li>Com explicativa numérica</li>
</ol>
</li>
</ol>
</li>
</ol>
<p>Para cada gráfico, iremos ver (i) como desenhar o gráfico e (ii) como interpretá-lo. A explicação do ponto (i) já diz muito sobre o ponto (ii), mas iremos tentar discriminar cada uma das análises especificamente.</p>
<p>Antes de continuar as explicações, precisamos explicar o que significa ser um gráfico univariado ou bivariado?.</p>
<p>Um gráfico univariado representa apenas uma única variável nele. Isso <strong>não significa que</strong> o gráfico tenha apenas um eixo. Na verdade, os gráficos univariados normalmente têm dois eixos. Então a quantidade de variáveis não diz exatamente respeito à quantidade de eixos.</p>
<p>Já o gráfico bivariado representa duas variáveis nele, em que uma variável é a variável resposta e a outra variável é a variável explicativa. A variável resposta é aquela que nós queremos compreender; e a variável explicativa é a variável que queremos usar para explicar a variável resposta.</p>
<p>Vamos dar um exemplo para compreender o que são as variáveis explicativa e resposta. Ao analisar instância recursal, podemos nos interssar por ver se a reforma da decisão de primeiro grau é afetada pelo valor da causa. Então surge a seguinte pergunta de psquisa: será que causas de valores maiores tendem a ser menos reformadas? Veja que a relação que queremos avaliar tem uma ordem certa: importa dizer que é o valor da causa que explica a reforma, e não o contrário, de que é a reforma da sentença que explica o valor da causa. Essas duas relações são possíveis de serem analisadas (apesar de que faz pouco sentido teórico explicar o valor da causa pela reforma). O importante é notar que essas duas relações são distintas, e aquilo em que elas se distinguem é justamente o que cada uma delas considera como variável resposta e como variável explicativa. Na pergunta de se a reforma da sentença é afetada pelo valor da causa, a variável “reforma” é a variável resposta (ou seja, a variável que queremos compreender); e a variável “valor da causa” é a variável explicativa (ou seja, a variável que queremos que explique a variável resposta). Em termos matemáticos, a variável resposta é a variável Y e a variável explicativa é a variável X.</p>
<section id="visualizações-de-variáveis-categóricas" class="level3" data-number="4.3.1"><h3 data-number="4.3.1" class="anchored" data-anchor-id="visualizações-de-variáveis-categóricas">
<span class="header-section-number">4.3.1</span> Visualizações de variáveis categóricas</h3>
<section id="gráficos-univariados" class="level4" data-number="4.3.1.1"><h4 data-number="4.3.1.1" class="anchored" data-anchor-id="gráficos-univariados">
<span class="header-section-number">4.3.1.1</span> Gráficos univariados</h4>
<p>Os gráficos univariados de variáveis categóricas são marcados por conterem sempre duas informações: as categorias analisadas e a contagem ou proporção dessas categorias. Por mais que os gráficos tenham duas dimensões, eles não contém duas “variáveis”. A única variável são as categorias; a contagem/proporção é simplesmente um atributo dessa variável. Vamos ver duas visualizações mais difundidas desse tipo de variável. Para mais exemplos, ver <a href="https://www.data-to-viz.com/">From data to Viz</a>.</p>
<section id="gráfico-de-barras" class="level5" data-number="4.3.1.1.1"><h5 data-number="4.3.1.1.1" class="anchored" data-anchor-id="gráfico-de-barras">
<span class="header-section-number">4.3.1.1.1</span> Gráfico de barras</h5>
<p>O gráfico de barras é o principal meio de visualizar variáveis categóricas. Ele contém dois eixos: a variável categórica e a contagem/proporção. Não importa o eixo em que cada uma dessas informações está. A variável pode ser apresentada tanto no eixo x (horizontal), como no eixo y (vertical, também chamado de gráfico de colunas), conforme a <a href="#fig-vis-barras">Figura&nbsp;<span>4.4</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-vis-barras" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-vis-barras-1.png" class="img-fluid figure-img" width="2700"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.4: Gráficos de barras</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>O gráfico é simples, bem como a sua interpretação. Basta verificar a contagem de cada categoria. Usualmente, tira-se desses gráficos a conclusão de quais grupos são mais relevantes, qual é a tendência de resposta de determinada categoria. No caso em tela, observamos que os processos de consumo, em segunda instância, tendem a não ser reformados.</p>
</section><section id="gráfico-de-setores-pizza" class="level5" data-number="4.3.1.1.2"><h5 data-number="4.3.1.1.2" class="anchored" data-anchor-id="gráfico-de-setores-pizza">
<span class="header-section-number">4.3.1.1.2</span> Gráfico de setores (pizza)</h5>
<p>O segundo tipo de visualização categórica são os gráficos de setores, ou gráficos de pizza (ou <em>pie charts</em>, em inglês). Esta visualização é uma forma muito frequente de apresentar os dados. A diferença dos gráficos de pizza para os gráficos de barras é que eles apresentam informações dispostas, não lado a lado, mas dentro de um círculo. O círculo inteiro compreende todas as observações possíveis, enquanto as suas ramificações (ou pedaços de pizza) representam a parcela do todo que diz respeito a uma determinada categoria.</p>
<p>Esse gráfico, apesar de ser amplamente utilizado, ele traz um problema de visualização. Por mais que o gráfico funcione bem para representar duas ou três categorias, com mais categorias do que isso ele passa a não ser muito funcional.</p>
<p>Aqui vamos replicar o exemplo elaborado pelo Data to Viz em <a href="https://www.data-to-viz.com/caveat/pie.html">The issue with pie chart</a>. O exemplo que eles dão parte da seguinte pergunta: Tente descobrir nos três grupos abaixo qual é o grupo com mais observaçẽs.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="assets/img/pie-datatoviz.png" class="img-fluid" style="width:100.0%"></p>
</div>
</div>
<p>A resposta deveria ser, para a primeira pergunta, que no primeiro gráfico, o maior grupo é o E; no segundo, o C; e no terceiro, o A. Acontece que, por causa da forma como os dados estão dispostos, é difícil chegar a essa conclusão, enquanto, se repetíssemos a pergunta para os mesmos dados dispostos em barras, essa pergunta seria trivial.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="assets/img/bar-datatoviz.png" class="img-fluid" style="width:100.0%"></p>
</div>
</div>
<p>Então, a questão com os gráficos de pizza é que eles possuem um iminente problema de comunicação e interpretação. A assimilação desses gráficos não é intuitiva, muitas vezes, sequer possível a olho nu. Dessa forma, deve-se preferir, na maioria das vezes, a utilização de gráficos de barras no lugar de gráficos de pizza. Recomenda-se que se utilize gráficos de pizza para representar 2 ou, no máximo, 3 categorias. Mais do que isso, a visualização fica prejudicada.</p>
</section></section><section id="gráficos-bivariados-com-explicativa-categórica" class="level4" data-number="4.3.1.2"><h4 data-number="4.3.1.2" class="anchored" data-anchor-id="gráficos-bivariados-com-explicativa-categórica">
<span class="header-section-number">4.3.1.2</span> Gráficos bivariados (com explicativa categórica)</h4>
<section id="gráfico-de-barras-1" class="level5" data-number="4.3.1.2.1"><h5 data-number="4.3.1.2.1" class="anchored" data-anchor-id="gráfico-de-barras-1">
<span class="header-section-number">4.3.1.2.1</span> Gráfico de barras</h5>
<p>O mesmo gráfico de barras que pode representar uma única variável, pode ser usado para representar duas variáveis categóricas. Neste caso, não mudamos os eixos. O que fazemos, no lugar, é “quebrar” cada uma das categorias do eixo categórico em algum subgrupo. Por exemplo, na <a href="#fig-barras-2var">Figura&nbsp;<span>4.5</span></a>, pegamos as categorias referentes a “decisões de segunda instância” e quebramos pelo tipo de litígio. Há 4 tipos de litígio possíveis: uma pessoa física (PF) no polo ativo contra alguma não-pessoa física (nPF), tal como uma empresa, um espólio ou o Poder Público (PF-nPF); uma pessoa física contra outra pessoa física (PF-PF); uma pessoa não física no polo ativo, contra uma pessoa física (nPF-PF); ou uma disputa entre duas pessoas não físicas (nPF-nPF).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-barras-2var" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-barras-2var-1.png" class="img-fluid figure-img" width="3600"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.5: Gráficos de barras com duas variáveis, empilhado.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Essa “quebra” pode ser feita de diversas maneiras. A escolha entre cada uma delas dependerá dos propósitos do gráfico, ou até mesmo do estilo do próprio pesquisador. A <a href="#fig-barras-2var2">Figura&nbsp;<span>4.6</span></a> traz outra forma de realizar essa quebra.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-barras-2var2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-barras-2var2-1.png" class="img-fluid figure-img" width="2400"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.6: Gráficos de barras com duas variáveis, lado a lado.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>O que precisamos compreender é a complexidade que essa segunda variável adiciona à interpretação do gráfico. No gráfico de barras univariado, podíamos comparar apenas o tamanho de cada um dos desfechos da sentença. Na <a href="#fig-highlight-barras">Figura&nbsp;<span>4.7</span></a>, damos um exemplo de um tipo de comparação possível a partir do gráfico univariado, em que comparamos os os grupos “Reformou” com “Não reformou”.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-highlight-barras" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-highlight-barras-1.png" class="img-fluid figure-img" width="2700"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.7: Gráfico de barras com comparação entre os grupos ‘Reformou’ e ‘Não reformou’</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Com os gráficos de barras bivariados, outras comparações são possíveis. No caso, podemos realizar 2 novas comparações. A primeira comparação possível é aquela em que fixamos a variável de interesse para compararmos a variável explicativa. No nosso caso, isso significa comparar, dentro de um único desfecho da sentença, alguns tipos de litígio. Vemos um exemplo desta comparação na <a href="#fig-highlight-bivar">Figura&nbsp;<span>4.8</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-highlight-bivar" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-highlight-bivar-1.png" class="img-fluid figure-img" width="2700"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.8: Contagens de não reforma e configuração das partes.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>A segunda nova comparação possível é aquela em que fixamos a variável explicativa, ou seja, a variável de quebra, e a analisamos através de todas as categorias de interesse. Vemos um exemplo disto na <a href="#fig-highlight-bivar2">Figura&nbsp;<span>4.9</span></a>, em que olhamos para o tipo de litígio “PF-nPF” para todos os três tipos de desfechos possíveis das decisões de segunda instância.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-highlight-bivar2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-highlight-bivar2-1.png" class="img-fluid figure-img" width="2700"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.9: Contagens de reforma/não reforma e configuração das partes.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Notemos, então, que adicionar uma nova variável ao gráfico de barras, para torná-lo bivariado, aumenta a sua complexidade de análise. Isso pode ser bom, pois nos permite visualizar novas relações, mas também pode ser ruim, na medida em que dificulta a interpretação do gráfico.</p>
</section></section><section id="gráficos-bivariados-com-explicativa-numérica" class="level4" data-number="4.3.1.3"><h4 data-number="4.3.1.3" class="anchored" data-anchor-id="gráficos-bivariados-com-explicativa-numérica">
<span class="header-section-number">4.3.1.3</span> Gráficos bivariados (com explicativa numérica)</h4>
<p>Nos gráficos de barras bivariados que mostramos acima, a variável explicativa era categórica (no caso, “Tipo de litígio”). A partir dessa variável explicativa categórica, nós pudemos “quebrar” as barras em categorias menores. Vimos diversas formas de realizar essa quebra, bem como as novas interpretações que isso permitia realizar.</p>
<p>Poderíamos nos perguntar, então, o que aconteceria se, no lugar de “Tipo de litígio”, colocássemos alguma variável numérica contínua, tal como “valor da ação”? Como o gráfico ficaria?</p>
<p>Temos de ter cautela com essa pergunta, pois, por mais intuitivo que seja se fazer uma pergunta dessas, esse tipo de visualização só faz sentido em um contexto bem específico: o de regressão. Veremos regressões apenas mais para frente do livro. Quando chegarmos lá, poderemos completar essa explicação.</p>
</section></section><section id="visualizações-de-variáveis-quantitativas" class="level3" data-number="4.3.2"><h3 data-number="4.3.2" class="anchored" data-anchor-id="visualizações-de-variáveis-quantitativas">
<span class="header-section-number">4.3.2</span> Visualizações de variáveis quantitativas</h3>
<section id="gráficos-univariados-1" class="level4" data-number="4.3.2.1"><h4 data-number="4.3.2.1" class="anchored" data-anchor-id="gráficos-univariados-1">
<span class="header-section-number">4.3.2.1</span> Gráficos univariados</h4>
<p>No caso das variáveis quantitativas, também temos formas de representá-las de forma univariada. São duas as visualizações mais frequentes: o histograma e o boxplot.</p>
<section id="histograma" class="level5" data-number="4.3.2.1.1"><h5 data-number="4.3.2.1.1" class="anchored" data-anchor-id="histograma">
<span class="header-section-number">4.3.2.1.1</span> Histograma</h5>
<p>O histograma assemelha-se muito ao gráfico de barras. Eles não devem, entretanto, ser confundidos. O histograma representa variáveis quantitativas contínuas, enquanto o gráfico de barras representa categorias. A diferença essencial é que, enquanto no gráfico de barras nos interesse o tamanho de cada barra, no histograma nos interessa mais a distribuição geral dos dados ao longo do eixo. A <a href="#fig-histograma-tempo">Figura&nbsp;<span>4.10</span></a> traz um exemplo de um histograma com o valor de tempo de cada processo em dias.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-histograma-tempo" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-histograma-tempo-1.png" class="img-fluid figure-img" width="2700"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.10: Histograma simples</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Trabalhando em cima deste exemplo, vamos compreender (a) como se formam as barras do histograma; (b) como interpretar este gráfico; (c) propriedades do histograma; (d) problemas de visualização e transformação dos dados.</p>
<p>A começar pela formação das barras do histograma, precisamos voltar um pouco na natureza das variáveis quantitativas. Existem dois tipos de variáveis quantitativas: as discretas e as contínuas. As discretas representam apenas a contagem de certo número, por exemplo, quando se deseja saber a quantidade de juízes que determinado tribunal possui. Essa quantidade, que expressa apenas uma contagem, será uma variável discreta. As características dessa variável são que ela não pode assumir nem valores negativos, nem valores fracionados, mas apenas valores inteiros. As variáveis contínuas, por outro lado, seriam variáveis que expressam números reais, podendo por natureza envolver números negativos ou fracionados. Acontecem alguns casos em que os números negativos não fazem sentido no mundo real, por exemplo, quando temos uma variável contínua sobre tempos. Por exemplo, se tivermos uma variável sobre o tempo que demora para um processo morrer, não faz sentido que essa variável indique “-100 dias”.</p>
<p>Essa recapitulação dos tipos de variáveis quantitativas é importante porque os histogramas representam apenas variáveis quantitativas <em>contínuas</em>, e isso traz um problema para a representação gráfica. O problema é, se eu for fazer uma barra para cada valor possível, tratando eles como categorias próprias, eu teria, teoricamente, infinitas barras. Por exemplo, eu poderia ter, em uma variável de valor, uma barra para todos os processos cujo valor da ação é de R$ 1,00; e depois outra barra para os valores de R$ 1,10. Mas entre uma barra eu poderia ter R$ 1,05; ou ainda 1,025, etc.</p>
<p>A fim de eliminar esse problemas das barras infinitas, cada barra do histograma acaba representando um intervalo, de modo que nenhuma barra represente um único valor, mas sim um intervalo de valores. Assim, no lugar de uma barra para o valor de R$ 1,00, temos uma barra para os valores de R$ 1,00 a R$ 2,00, por exemplo. O tamanho desse intervalo é variável, não é fixo; ele não está predeterminado. O que precisamos saber deste intervalo é que ele é fechado no início e aberto no final, ou seja, se tivermos o intervalo de R$ 1,00 a R$ 2,00 e outro intervalo de R$ 2,00 a R$ 3,00, isso significa que um processo cujo valor da causa seja R$ 2,00, ele estará dentro do segundo intervalo e não do primeiro, mas o valor da causa for de R$ 1,99, ele estará dentro do primeiro intervalo mesmo.</p>
<p>A representação dos intervalos segue uma notação específica: para os intervalos fechados, representamos um colchete voltado para o número; para os intervalos abertos, um colchete “de costas” para o número. A seguir, damos alguns exemplos para compreender melhor essa notação.</p>
<ul>
<li>[1,10] significa que o intervalo é fechado no 1 (porque usamos um colchete) e fechado no 10 (porque usamos um colchete);</li>
<li>[1, 10) significa que o intervalo é fechado no 1 (porque usamos um colchete) e aberto no 10 (porque usamos um parêntese);</li>
<li>(1, 10] significa que o intervalo é aberto no 1 (porque usamos um parêntese) e fechado no 10 (porque usamos um colchete);</li>
<li>(1, 10[ significa que o intervalo é aberto no 1 (porque usamos um parêntese) e aberto no 10 (porque usamos um parêntese).</li>
</ul>
<p>A partir da criação dos intervalos, cada uma das observações da base será colocada dentro de uma das categorias especificadas. Assim, cada um dos intervalos terá uma contagem (igual ao caso do gráfico de barras). Todas as categorias devem ter exatamente o mesmo tamanho. Assim, se foi criada uma categoria que vai do 1 ao 10, então a próxima categoria <em>tem que ser</em> do 10 ao 19, pois elas devem ter exatamente o mesmo tamanho.</p>
<p>Mexer no tamanho das categorias pode gerar histogramas diferentes. Veja o mesmo histograma do exemplo acima com três variações do tamanho dos intervalos de cada barra na <a href="#fig-varios-histogramas">Figura&nbsp;<span>4.11</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-varios-histogramas" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-varios-histogramas-1.png" class="img-fluid figure-img" width="2400"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.11: O mesmo histograma com intervalos distintos para as barras</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Uma vez que descobrimos como que as barras do histograma são criadas, podemos passar para o tópico seguinte: como interpretar? No caso do histograma, não nos interessa muito saber a contagem exata de cada “categoria” (até porque as barras não representam categorias, mas apenas intervalos arbitrários). A contagem específica de cada categoria era uma informação importante quando olhávamos para o gráfico de barras, mas no histograma, não é essa informação por que estamos buscando. O essencial do histograma é ver a <em>distribuição</em> dos dados como um todo, e não cada barra.</p>
<p>Voltando ao nosso exemplo, conseguimos ver que existe uma barra cuja contagem de casos está acima dos 300 casos. Não nos importa saber a contagem exata desta barra. Ao que devemos nos atentar é que a distribuição do tempo dos processos se dá de forma concentrada na esquerda. Esse tipo de distribuição chamamos de distribuição assimétrica para a direita. A indicação da assimetria diz respeito à localização da “cauda” do gráfico. No nosso caso, temos uma série de valores concentrados no início, em tempos mais baixos, e alguns poucos casos esparramados no fim, em tempos mais longos. Então, quando dizemos que a distribuição é assimétrica “para a direita” estamos nos referindo à assimetria que estes casos da cauda do gráfico criaram.</p>
<p>Como estamos falando, o mais importante dos histogramas é verificar a distribuição dos dados, e não a contagem específica de cada barra. O que precisamos falar ainda é: quais são as distribuições possíveis? Existem muitas distribuições, mas destacamos 3 principais: a distribuição simétrica, a distribuição assimétrica para a direita e a distribuição assimétrica para a esquerda. Essas distribuições estão resumidas na <a href="#fig-distribuicoes-sim">Figura&nbsp;<span>4.12</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-distribuicoes-sim" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-distribuicoes-sim-1.png" class="img-fluid figure-img" width="2100"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.12: Distribuições</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>A propriedade importante do histograma diz respeito à posição relativa entre média e mediana. Queremos sempre determinar onde os dados estão concentrados. Para tanto, as medidas de resumo que indicam tendência central são excelentes. Lembrando, temos três medidas: a média, a mediana e a moda. A média e a mediana se diferenciam porque a mediana é considerada robusta (isto é, ela não era influenciada pelos valores extremos), enquanto a média é considerada uma medida não robusta. Assim, quando estamos diante de distribuições assimétricas – sejam elas para a esquerda ou para a direita –, a média será afetada pelos valores que estão na cauda, enquanto a mediana não. Essa diferença entre as duas medidas cria um importante atributo para interpretarmos o histograma. O que acontece é que, em distribuições simétricas, a média e a medina irão se sobrepor, assumindo o mesmo valor, ou valores muito próximos, enquanto, no caso das distribuições assimétricas, os valores da média e da mediana irão ficar descompassados. Assim, podemos visualizar, a partir do histograma, como que a média e a mediana se comportam, conforme a <a href="#fig-distribuicoes-sim-lab">Figura&nbsp;<span>4.13</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-distribuicoes-sim-lab" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-distribuicoes-sim-lab-1.png" class="img-fluid figure-img" width="2100"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.13: Distribuições</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>A partir desses três histogramas, podemos tirar as seguintes propriedades:</p>
<ul>
<li>Distribuição assimétrica para esquerda: Média &lt; Mediana</li>
<li>Distribuição simétrica: Média = Mediana</li>
<li>Distribuição assimétrica para direita: Média &gt; Mediana</li>
</ul>
<p>Por fim, podemos nos atentar à última questão com os histogramas: problemas de visualização e a transformação dos dados. O que acontece é que muitas variáveis possuem uma distribuição muito assimétrica, de forma que existem muitos valores concentrados em um pico e pouquíssimos valores dispersos em uma grande amplitude. Isso é extremamente frequente em todos os dados envolvendo valores. Até agora, estávamos usando como exemplo apenas gráficos com tempos, justamente porque as visualizações com valores são muito difíceis. Na <a href="#fig-histograma-valor-2">Figura&nbsp;<span>4.14</span></a>, temos um exemplo do que acontece com os valores na base de dados de consumo.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-histograma-valor-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-histograma-valor-2-1.png" class="img-fluid figure-img" width="2700"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.14: Histograma de valores</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>O que acontece é que existem pouquíssimos valores <em>muito altos</em> (maiores do que R$ 40 milhões) e uma massa de casos com valores <em>muito baixos</em>. Uma assimetria deste tamanho faz parecer que todos os casos possuem um valor de causa igual a zero. Entretanto, isso não é verdade. Se, simplesmente retirarmos da base 10% dos processos, envolvendo os maiores valores, obtemos o histograma da <a href="#fig-hist-valores-filter">Figura&nbsp;<span>4.15</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-hist-valores-filter" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-hist-valores-filter-1.png" class="img-fluid figure-img" width="2700"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.15: Histograma de valores (filtrando os 10% maiores processos)</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>A partir dessa figura conseguimos perceber que são somente os processos acima do quantil(0.9) que estão prejudicando a visualização do histograma. Diante desse problema, o que devemos fazer?</p>
<p>Uma solução já foi dada, que foi justamente excluir da base os processos que estão atravancando a análise e depois analisá-los separadamente. Temos um bom exemplo disto na seguinte reportagem do Nexo Jornal <a href="https://www.nexojornal.com.br/grafico/2015/11/11/O-saldo-do-cinema-brasileiro">O saldo do cinema brasileiro</a>. Essa solução pode servir para alguns casos, principalmente quando estamos falando da função comunicativa das visualizações. Entretanto, para a função exploratória, essa função nem sempre é adequada, pois, como ela fragmenta a base, ela perde de vista a distribuição do todo.</p>
<p>Uma solução muito frequente para este problema, então, é ao invés de excluir os dados, transformá-los. A transformação mais comum é a transformação em log10. No nosso exemplo, iríamos então transformar os valores exatos de cada causa, para os valores em log de base 10. Assim, aquele histograma da <a href="#fig-hist-valores-filter">Figura&nbsp;<span>4.15</span></a> ficaria com esta aparência depois da transformação em log, conforme a <a href="#fig-hist-valores-log">Figura&nbsp;<span>4.16</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-hist-valores-log" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-hist-valores-log-1.png" class="img-fluid figure-img" width="2700"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.16: Histograma de valores (com transformação em log de base 10)</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Por mais que a visualização das barras fique melhorada, a interpretação deste gráfico fica prejudicada, pois agora temos que interpretar o valor em log. O que significa que existe uma concentração de processos com valor em log igual a 4? Isso significa que existe uma concentração de processos em torno de <span class="math inline">\(10^4=10.000\)</span>, ou seja, em torno de R$ 10.000,00. Por mais que a interpretação fique dificultada, a visualização decerto fica melhor.</p>
<p>A melhor alternativa para se apresentar um histograma em escala logarítmica, talvez seja a de substituir os valores em log pelos valores reais. A única atenção que temos de ter neste caso é para não se deixar confundir com a escala do gráfico (<a href="#fig-hist-valores-log2">Figura&nbsp;<span>4.17</span></a>: a escala continua sendo logarítmica, apesar de as marcações não indicarem isso.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-hist-valores-log2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-hist-valores-log2-1.png" class="img-fluid figure-img" width="2700"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.17: Histograma de valores (com transformação em log de base 10)</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section><section id="boxplot" class="level5" data-number="4.3.2.1.2"><h5 data-number="4.3.2.1.2" class="anchored" data-anchor-id="boxplot">
<span class="header-section-number">4.3.2.1.2</span> Boxplot</h5>
<p>A próxima visualização importante para variáveis numéricas é o boxplot. O boxplot é um gráfico que apresenta as estatísticas resumo de uma determinada variável, ao invés de apresentar as unidades amostrais, tal como ocorre no histograma. Para explicar o boxplot, vamos falar de 3 pontos: (a) como se forma o boxplot; (b) como interpretar este gráfico; e (c) problemas relacionados a ele.</p>
<p>Para tratar da formação do boxplot, é importante começar visualizando-o, para que possamos compreender as diferentes partes que o compõem.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-boxplot1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-boxplot1-1.png" class="img-fluid figure-img" width="2400"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.18: Exemplos de boxplot, um em pé e outro deitado</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Com a imagem do boxplot em mente, podemos dissecá-lo em três partes, para fins didáticos: o centro, os bigodes e os pontos.</p>
<p>O centro é o retângulo que fica no meio do boxplot. Esse retângulo é definido por três parâmetros. Para entendê-los, precisamos nos lembrar dos quantis empíricos e, mais especificamente, dos quartis. Essa matéria foi vista no capítulo anterior, mas ela é importante neste contexto porque o centro do boxplot é definido justamente pelos três quartis: o quartil superior, a mediana e o quartil inferior. Basicamente, o perímetro externo do centro do boxplot é delimitado pelos quartis superior e inferior e a linha que corta o retângulo boxplot é a mediana. Não necessariamente a mediana está ao centro do retângulo. Mais para frente veremos o que significa a posição da linha mediana dentro do retângulo. O que importa, neste momento, é saber que o centro do boxplot é definido pelos três quartis empíricos, sendo que a mediana representa a linha que corta o retângulo central.</p>
<p>A seguir, a segunda parte do boxplot são os bigodes. Existem dois bigodes, um para cima e outro para baixo. Ambos se formam da mesma maneira: eles se estendem do perímetro externo do retângulo central até 3/2 do IQR. Vale lembrar que, conforme vimos no capítulo anterior, IQR (Interquartile Range) representa a amplitude dos quartis superior e inferior, ou seja, ele é calculado pela diferença do quartil superior (75%) com o quartil inferior (25%). Dessa forma, o IQR diz qual é a amplitude em que se encontram os 50% centrais dos dados. Lembrando desta informação, podemos voltar aos bigodes. Os bigodes são linhas que se estendem desde a área externa do retângulo central até um ponto que representa 3/2 do IQR. O bigode inferior, se inicia do quartil inferior e vai até -3/2 IQR; enquanto o bigode superior se inicia do quartil superior e vai até 3/2 IQR.</p>
<p>Por que usamos o valor de 3/2 do IQR? Isso acontece porque, em distribuições normais, 3/2 do IQR representa 99% de todos os dados. Essa afirmação faz pouco sentido agora, entretanto, mais para frente do livro, daremos sentido a ele, definindo melhor o que significa uma distribuição normal e como podemos saber que 3/2 do IQR representa 99% dos dados. Essa última afirmação está relacionada a algumas propriedades da distribuição normal.</p>
<p>É preciso saber também, sobre os bigodes, que nem sempre o bigode, de fato, vai até os 3/2 do IQR. Isso se dá porque, no boxplot, o bigode pode ir até os 3/2 do IQR, entretanto, ele só irá até a última observação antes de esse ponto chegar. Isso significa que mesmo se existirem pontos além dos 3/2 do IQR, se o último ponto antes desse limite estiver, por exemplo, a <span class="math inline">\(\frac 1 2\)</span> do IQR, então o bigode vai andar somente até esse ponto.</p>
<p>E se existir algum ponto além dos 3/2 do IQR? Então o bigode irá representar as observações <strong>antes</strong> de se passar desse limite; e os valores que passarem deste limite serão representados com pontos. Daí a explicação da terceira parte do boxplot, os pontos. Os pontos, nada mais são do que os dados que estão além dos 3/2 de IQR, seja para cima ou para baixo. Se não houver dados acima desses 3/2 de IQR, então não haverá pontos. Essa é a única parte do gráfico que pode ou não aparecer, todas as demais são partes essenciais do gráfico.</p>
<p>Antes de prosseguirmos a explicação para outras questões relacionadas ao boxplot, vamos montar parte a parte de um boxplot a partir de um conjunto de dados. O conjunto de dados que utilizaremos é a base consumo. Essa base contém 1000 observações, cuja unidade amostral são processos de consumo. Vamos, para os fins dessa explicação, amostrar somente 30 processos.</p>
<p>O primeiro passo para montar o boxplot é determinar os eixos do boxplot. É preciso ter clareza de que o boxplot que estamos vendo agora é univariado, ou seja, ele possui apenas um eixo. Este eixo é o eixo que contém os valores da variável numérica. No nosso caso, será o eixo de valor da causa. Não importa se esse eixo for o x ou o y, pois o boxplot pode ser apresentado tanto na horizontal como na vertical.</p>
<p>O segundo passo é realizar os cálculos das estatísticas de resumo do nosso conjunto de dados. São 5 informações de que precisamos (máximo, mínimo, mediana, quartil superior e inferior), e outras 7 medidas decorrentes dessas 5 (IQR, o limite superior do bigode, o limite inferior do bigode, o ponto superior, o ponto inferior e os potenciais outliers nos limites inferior e superior). A <a href="#tbl-medidas-boxplot">Tabela&nbsp;<span>4.3</span></a> resume essas informações.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-medidas-boxplot" class="anchored">
<table class="table table-sm table-striped">
<caption>Tabela&nbsp;4.3: Medidas resumo que compõem o boxplot.</caption>
<thead><tr class="header">
<th style="text-align: left;">medidas</th>
<th style="text-align: left;">parte do boxplot</th>
<th style="text-align: left;">valores</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">valor máximo</td>
<td style="text-align: left;">bigodes</td>
<td style="text-align: left;">R$ 82.279,86</td>
</tr>
<tr class="even">
<td style="text-align: left;">quartil superior</td>
<td style="text-align: left;">centro</td>
<td style="text-align: left;">R$ 22.370,00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mediana</td>
<td style="text-align: left;">centro</td>
<td style="text-align: left;">R$ 14.066,00</td>
</tr>
<tr class="even">
<td style="text-align: left;">quartil inferior</td>
<td style="text-align: left;">centro</td>
<td style="text-align: left;">R$ 10.003,23</td>
</tr>
<tr class="odd">
<td style="text-align: left;">valor mínimo</td>
<td style="text-align: left;">bigodes</td>
<td style="text-align: left;">R$ 395,26</td>
</tr>
<tr class="even">
<td style="text-align: left;">IQR</td>
<td style="text-align: left;">bigodes</td>
<td style="text-align: left;">R$ 12.366,77</td>
</tr>
<tr class="odd">
<td style="text-align: left;">quartil superior + 3/2 IQR</td>
<td style="text-align: left;">bigodes</td>
<td style="text-align: left;">R$ 40.920,16</td>
</tr>
<tr class="even">
<td style="text-align: left;">quartil inferior - 3/2 IQR</td>
<td style="text-align: left;">bigodes</td>
<td style="text-align: left;">R$ -8.546,94</td>
</tr>
<tr class="odd">
<td style="text-align: left;">último ponto superior</td>
<td style="text-align: left;">bigodes</td>
<td style="text-align: left;">R$ 40.400,74</td>
</tr>
<tr class="even">
<td style="text-align: left;">último ponto inferior</td>
<td style="text-align: left;">bigodes</td>
<td style="text-align: left;">R$ 395,26</td>
</tr>
<tr class="odd">
<td style="text-align: left;">quantidade de pontos superiores</td>
<td style="text-align: left;">pontos</td>
<td style="text-align: left;">3 pontos</td>
</tr>
<tr class="even">
<td style="text-align: left;">quantidade de pontos inferiores</td>
<td style="text-align: left;">pontos</td>
<td style="text-align: left;">0 pontos</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>A começar pelo centro do boxplot, ele está contido dentro dos limites dos quartis superior e inferior e, portanto, ele começa, no ponto R$ 10.003,23 e acaba no ponto R$ 22.370,00. A mediana, que corta o retângulo central, está no ponto R$ 14.066,00. Percebemos já, com isso, que a mediana não está no centro. O retângulo central está representado na <a href="#fig-boxplot-desenho1">Figura&nbsp;<span>4.19</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-boxplot-desenho1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-boxplot-desenho1-1.png" class="img-fluid figure-img" width="2400"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.19: Boxplot sem bigodes</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>A seguir, para construir os bigodes, temos que calcular o IQR. O IQR é simplesmente a diferença do quartil superior com o quartil inferior, dando R$ 12.366,77. Então 3/2 do IQR representa R$ 18.550,15 (3/2 * 12.366,77). Com base nisso, podemos calcular os bigodes inferior e superior.</p>
<p>O bigode superior pode andar 18.550,15 unidades acima do quartil superior, podendo assumir, portanto, no máximo o valor de R$ 40.920,16. Quanto ao bigode inferior, precisamos subtrair 3/2 do IQR do quartil inferior, resultando em R$ -8.546,94. Como não é possível que o valor da causa seja negativo, então esse número, na verdade, equivale simplesmente a R$ 0,00, ou seja, o menor valor que o bigode inferior pode assumir é zero. O zero está contido dentro do limite do bigode inferior, então não haverá nenhum valor além do limite inferior para o bigode e, portanto, não haverá nenhum ponto na região inferior. Os limites dos bigodes estão representados na <a href="#fig-boxplot-desenho2">Figura&nbsp;<span>4.20</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-boxplot-desenho2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-boxplot-desenho2-1.png" class="img-fluid figure-img" width="2400"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.20: Boxplot com bigodes estendidos</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Mesmo sabendo os pontos máximo que os bigodes poderão assumir, isso ainda não nos diz onde os bigodes irão parar, uma vez que não necessariamente (e via de regra não é assim) o maior valor dentro da região dos bigodes é de fato o maior valor possível. No nosso caso, a observação de maior valor que está dentro do bigode inferior é o valor mínimo, de R$ 395,26; e a observação de maior valor dentro do limite do bigode superior é o ponto R$ 40.400,74. Os bigodes estão representados na <a href="#fig-boxplot-desenho3">Figura&nbsp;<span>4.21</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-boxplot-desenho3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-boxplot-desenho3-1.png" class="img-fluid figure-img" width="2400"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.21: Boxplot com bigodes cortados</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Por fim, uma vez que os bigodes foram construídos, falta apenas a última parte dos boxplots, que são os pontos. Na parte inferior do gráfico, como vimos, como o limite inferior vai até um número negativo, mas os valores reais podem ir, no máximo, até R$ 0,00, então não há pontos na parte inferior. Na parte superior do gráfico, há três pontos que extrapolam o limite do gráfico. Estes pontos estão representados na <a href="#fig-boxplot-desenho4">Figura&nbsp;<span>4.22</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-boxplot-desenho4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-boxplot-desenho4-1.png" class="img-fluid figure-img" width="2400"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.22: Boxplot com bigodes cortados e valores atípicos</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Com a explicação de como construir o boxplot, seguida de um exemplo, podemos prosseguir ao segundo ponto importante a respeito dos boxplots: como interpretar os boxplots? Os boxplots, assim como os histogramas, indicam distribuições. Então, assim como vimos alguns tipos de distribuições nos histogramas, podemos verificar como essas distribuições reverberam na construção dos boxplots. Na <a href="#fig-distribuicoes-boxplot">Figura&nbsp;<span>4.23</span></a>, vemos a relação do boxplot com as diferentes distribuições existentes.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-distribuicoes-boxplot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-distribuicoes-boxplot-1.png" class="img-fluid figure-img" width="2400"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.23: Distribuições e boxplots</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>O que podemos notar é que a posição da linha da mediana <em>dentro</em> do retângulo, indica o tipo de distribuição. Se a linha mediana está bem ao centro do retângulo central, então podemos concluir que a distribuição é simétrica; se a linha mediana está deslocada, então temos distribuições assimétricas. Com isso, percebemos a que elemento do retângulo central temos de nos atentar quando analisamos um boxplot.</p>
<p>A representação das distribuições por meio do boxplot é uma informação que já está presente no histograma e, nesse sentido, o boxplot não acrescenta muito à análise. Entretanto, o boxplot adiciona alguns elementos à visualização que não estão presentes no histograma. Há dois elementos importantes para a análise.</p>
<p>Primeiro, o boxplot consegue destacar os dois quartis centrais (o segundo e o terceiro quartis), que, juntos, representam exatamente o meio dos dados. Esse destaque nos permite inferir conclusões mais <em>robustas</em> a respeito do comportamento central do nosso conjunto. Se nos lembrarmos da discussão a respeito das medidas no capítulo anterior, uma medida <em>robusta</em> é uma medida menos suscetível aos valores extremos. Em muitos conjuntos de dados, os valores extremos distorcem os valores centrais. Então o boxplot consegue representar muito bem os valores centrais, dando destaque a esses valores. A Figura Y deixa em realce a porção dos dados que estão sendo representadas pelo retângulo central do boxplot.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-boxplot-normal" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-boxplot-normal-1.png" class="img-fluid figure-img" width="2400"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.24: Boxplot comparado com distribuição normal.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>O último ponto que merece destaque da interpretação dos boxplots são os pontos. A interpretação dos pontos é um ponto importante dos boxplots. Esses pontos indicam potenciais <em>outliers</em>. Esta é a primeira vez que falamos de outliers neste livro. Outliers são pontos que se diferem drasticamente do resto dos dados. Essa definição é muito genérica, pois ela é uma definição guarda-chuva. Mas ela não é suficiente. O que significa dizer que algum ponto “difere drasticamente” do resto dos dados? Como que eu meço o que são “o resto dos dados” para comparar com os pontos que “diferem drasticamente”?</p>
<p>Essas perguntas são essenciais, porque, na verdade, são justamente elas que dão contornos estatísticos para os outliers. Para cada resposta distinta que damos a essas perguntas, teremos uma definição distinta de outlier e existem muitas definições possíveis. A questão que une todos os outliers é que, em todas as suas acepções, os outliers distorcem os valores dos dados e são pontos cuja incidência na população é muito rara.</p>
<p>Há duas dificuldades ao lidar com outliers: a identificação e a solução. Sobre a identificação, o problema central é definir o ponto de corte dos dados: a partir de que valores poderemos dizer que existem outliers? A segunda questão é saber o que fazer depois de identificarmos os outliers? Retiramos eles da base? Olharmos separadamente para os outliers e os pontos centrais? Essas perguntas (de identificação e de solução) irão acompanhar o livro em muitos momentos, pois os outliers geram problemas que se manifestam de diversas maneiras na estatística. Voltaremos várias vezes nisso, portanto.</p>
<p>Neste momento introdutório, em que estamos vendo os outliers pela primeira vez, basta sabermos que eles são pontos discrepantes e que existe uma dificuldade tremenda em se determinar um ponto de corte para bater o martelo e dizer: “qualquer valor que ultrapasse essa fronteira, será considerado um outlier!”. No caso do boxplot, por causa da forma como ele é construído, todos os pontos representados no gráfico estão a 3/2 do IQR, contado a partir dos quartis inferior ou superior. Então, se assumirmos que todos os pontos que aparecem no boxplot são outliers, estaremos definido que “diferir drasticamente” significa “distanciar-se 3/2 do IQR contados a partir do quartil superior ou inferior”. Esse ponto de corte (quartil + 3/2 do IQR) é apenas uma definição dentre muitas possíveis para os outliers. Mas podemos usar critérios de corte mais brandos ou mais severos. Por isso dizemos que os pontos do boxplot indicam apenas “potenciais outliers”.</p>
<p>É importante pontuar aqui que o critério que usaremos para decidir o ponto de corte do outlier não deve ser um critério automático (como o é no caso dos pontos do boxplot). Para cada caso, para cada dado, para cada propósito, teremos um critério distinto para definir outliers. Cada critério resolve problemas distintos, mas gera vieses distintos também. Veremos com mais detalhes as formas de mensurar outliers ao longo do livro.</p>
<p>Dada toda essa discussão a respeito dos outliers, podemos voltar à interpretação dos boxplots. Em primeiro lugar, vimos que havia uma semelhança dos boxplots com os histogramas: ambos representavam distribuições dos dados, mas de formas distintos. Em seguida, passamos a ver duas características específicas do boxplot, que não estavam presentes no histograma: o foco no conjunto central e os outliers. Sobre este último ponto, vimos que os pontos que aparecem no boxplot representam apenas “potenciais outliers”, justamente porque eles assumem um critério automático de representação. Em alguns contextos, fará sentido assumir que os outliers são esses pontos mesmos; em outros, entretanto, não será assim.</p>
<p>Explicada a interpretação e a formação dos boxplots, resta somente abordar seus principais problemas. Há dois problemas: distribuições assimétricas e dados escassos.</p>
<p>A começar pelo problema das distribuições assimétricas, este é o mesmo problema que acontecia com o histograma, de que a visualização ficava impossibilitada por causa de distribuições muito assimétricas. Basta nos lembrarmos da <a href="#fig-histograma-valor-2">Figura&nbsp;<span>4.14</span></a>. No caso do boxplot, aqueles mesmos dados ficam representados conforme a <a href="#fig-boxplot-consumo">Figura&nbsp;<span>4.25</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-boxplot-consumo" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-boxplot-consumo-1.png" class="img-fluid figure-img" width="2700"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.25: Boxplot da variável consumo</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Vemos que o retângulo central está tão achatado, próximo do 0, que ele se torna uma linha. Perdemos, com isso, toda a noção das medidas centrais. Entretanto, se olharmos para a tabela de medidas para compôr este boxplot, veremos os seguintes valores, conforme a <a href="#tbl-boxplot-consumo">Tabela&nbsp;<span>4.4</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-boxplot-consumo" class="anchored">
<table class="table table-sm table-striped">
<caption>Tabela&nbsp;4.4: Tabela de estatísticas-resumo para construção do boxplot</caption>
<thead><tr class="header">
<th style="text-align: left;">medidas</th>
<th style="text-align: left;">parte do boxplot</th>
<th style="text-align: left;">valores</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">valor máximo</td>
<td style="text-align: left;">bigodes</td>
<td style="text-align: left;">R$ 3.608.780,16</td>
</tr>
<tr class="even">
<td style="text-align: left;">quartil superior</td>
<td style="text-align: left;">centro</td>
<td style="text-align: left;">R$ 24.799,48</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mediana</td>
<td style="text-align: left;">centro</td>
<td style="text-align: left;">R$ 13.590,47</td>
</tr>
<tr class="even">
<td style="text-align: left;">quartil inferior</td>
<td style="text-align: left;">centro</td>
<td style="text-align: left;">R$ 6.854,77</td>
</tr>
<tr class="odd">
<td style="text-align: left;">valor mínimo</td>
<td style="text-align: left;">bigodes</td>
<td style="text-align: left;">R$ 181,84</td>
</tr>
<tr class="even">
<td style="text-align: left;">IQR</td>
<td style="text-align: left;">bigodes</td>
<td style="text-align: left;">R$ 17.944,71</td>
</tr>
<tr class="odd">
<td style="text-align: left;">quartil superior + 3/2 IQR</td>
<td style="text-align: left;">bigodes</td>
<td style="text-align: left;">R$ 51.716,54</td>
</tr>
<tr class="even">
<td style="text-align: left;">quartil inferior - 3/2 IQR</td>
<td style="text-align: left;">bigodes</td>
<td style="text-align: left;">R$ -20.062,29</td>
</tr>
<tr class="odd">
<td style="text-align: left;">último ponto superior</td>
<td style="text-align: left;">bigodes</td>
<td style="text-align: left;">R$ 51.587,91</td>
</tr>
<tr class="even">
<td style="text-align: left;">último ponto inferior</td>
<td style="text-align: left;">bigodes</td>
<td style="text-align: left;">R$ 181,84</td>
</tr>
<tr class="odd">
<td style="text-align: left;">quantidade de pontos superiores</td>
<td style="text-align: left;">pontos</td>
<td style="text-align: left;">87 pontos</td>
</tr>
<tr class="even">
<td style="text-align: left;">quantidade de pontos inferiores</td>
<td style="text-align: left;">pontos</td>
<td style="text-align: left;">0 pontos</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Por esta tabela, vemos que o valor máximo que estará contido nos bigodes é de aproximadamente R$ 51 mil, entretanto, o valor máximo é de mais de R$ 53 milhões. Ou seja, o valor máximo que deveríamos visualizar não é nada perto do último ponto que observamos, por isso o centro do boxplot e os seus bigodes ficam achatados, parecendo uma linha no zero.</p>
<p>Quanto aos pontos, vemos que há 99 pontos acima do limite superior do boxplot. Entretanto, o que efetivamente conseguimos observar são apenas 4 pontos. Os demais 95 pontos estão todos concentrados, de forma que eles ficam indiscriminados entre si.</p>
<p>Então o primeiro problema diz respeito à visualização de dados muito dispersos e assimétricos. Como já vimos, isso pode ser resolvido colocando o gráfico em escala logarítmica. Na <a href="#fig-boxplot-consumo-log">Figura&nbsp;<span>4.26</span></a>, o gráfico está em log de base 10.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-boxplot-consumo-log" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-boxplot-consumo-log-1.png" class="img-fluid figure-img" width="2400"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.26: Boxplot dos valores em log na base 10</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Talvez o problema dessa transformação de variável seja que os parâmetros do gráfico se alteram. Vemos algo que não víamos nos outros boxplots representando esta mesma variável: pontos abaixo do bigode inferior! Isso acontece porque, com os valores em log, a variabilidade dos dados é muito diferente.</p>
<p>O outro problema dos boxplots são as informações que eles escondem. Como os boxplots apresentam somente as medidas de resumo, então eles escondem o tamanho da amostra. Veremos mais para frente que precisamos de grandes números de dados para realizar algumas inferências. Para um exemplo, ver a discussão do Data to Viz em <a href="https://www.data-to-viz.com/caveat/boxplot.html">The Boxplot and its pitfalls</a>.</p>
</section></section><section id="gráficos-bivariados-com-explicativa-categórica-1" class="level4" data-number="4.3.2.2"><h4 data-number="4.3.2.2" class="anchored" data-anchor-id="gráficos-bivariados-com-explicativa-categórica-1">
<span class="header-section-number">4.3.2.2</span> Gráficos bivariados (com explicativa categórica)</h4>
<p>Se antes estávamos vendo os gráficos univariados para variáveis numéricas, agora vamos ver como esses gráficos podem representar variáveis explicativas. Vamos começar com as variáveis explicativas categóricas, ou seja, gráficos que misturam uma informação numérica com outra categórica. Usualmente, usamos as categorias para explicar o comportamento da distribuição numérica.</p>
<p>A combinação de uma variável numérica com uma variável categórica não gera nenhum gráfico novo, mas apenas adiciona novas camadas de densidade para os dois gráficos de variáveis numéricas que já vimos: o histograma e o boxplot. Os exemplos serão breves, portanto.</p>
<section id="histograma-1" class="level5" data-number="4.3.2.2.1"><h5 data-number="4.3.2.2.1" class="anchored" data-anchor-id="histograma-1">
<span class="header-section-number">4.3.2.2.1</span> Histograma</h5>
<p>Para adicionar uma informação categórica nos histogramas, basta “quebrarmos” os dados em várias categorias, indicando como que cada categoria contribui para a distribuição geral. Na <a href="#fig-hist-com-shade">Figura&nbsp;<span>4.27</span></a> observamos o mesmo histograma de tempos que já vimos anteriormente, mas dividido pelo resultado final da decisão. Cruzando o tempo de decisão com o resultado da decisão poderíamos, por exemplo, investigar se os recursos protelatórios (cujo resultado é sempre negativo, ou, “Não reformou”).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-hist-com-shade" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-hist-com-shade-1.png" class="img-fluid figure-img" width="2700"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.27: Histograma para cada tipo de decisão</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section><section id="boxplot-1" class="level5" data-number="4.3.2.2.2"><h5 data-number="4.3.2.2.2" class="anchored" data-anchor-id="boxplot-1">
<span class="header-section-number">4.3.2.2.2</span> Boxplot</h5>
<p>Para o boxplot, podemos realizar o mesmo tipo de visualização, em que quebramos o boxplot principal em grupos menores. Isso nos permite comparar medianas e IQRs com maior facilidade.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/boxplot-com-cat-1.png" class="img-fluid figure-img" width="2700"></p>
<p></p><figcaption class="figure-caption">Histograma para cada tipo de decisão</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section></section><section id="gráficos-bivariados-com-explicativa-numérica-1" class="level4" data-number="4.3.2.3"><h4 data-number="4.3.2.3" class="anchored" data-anchor-id="gráficos-bivariados-com-explicativa-numérica-1">
<span class="header-section-number">4.3.2.3</span> Gráficos bivariados (com explicativa numérica)</h4>
<p>Ao contrário dos gráficos de variável numérica bivariados com uma explicativa categórica, que não formavam nenhum tipo de gráfico novo, quando cruzamos duas informações numéricas, aparece um novo gráfico, muito comum: o gráfico de dispersão (em inglês, scatter plot). Veremos esta visualização em mais detalhes a seguir.</p>
<section id="gráficos-de-dispersão" class="level5" data-number="4.3.2.3.1"><h5 data-number="4.3.2.3.1" class="anchored" data-anchor-id="gráficos-de-dispersão">
<span class="header-section-number">4.3.2.3.1</span> Gráficos de dispersão</h5>
<p>O gráfico de dispersão, como já dito, é usado para representar duas variáveis numéricas. Esse tipo de representação nos indica como que duas variáveis numéricas se relacionam. Há duas relações possíveis: uma relação positiva (isto é, quanto maior uma variável, maior a outra também), ou uma relação negativa (isto é, quanto mais de uma variável, menos eu tenho da outra). A <a href="#fig-dispersao">Figura&nbsp;<span>4.28</span></a> traz dois gráficos de dispersão, demonstrando as relações possíveis.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-dispersao" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-dispersao-1.png" class="img-fluid figure-img" width="2700"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.28: Gráficos de dispersão sobre litigiosidade</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>A linha que demonstra a relação não será tratada neste capítulo. Ela foi meramente ilustrativa para indicar o tipo de relação que está sendo representada entre as variáveis. O que importa é que, ao colocar, nos dois eixos, variáveis numéricas, conseguimos observar como essas variáveis se associam entre si.</p>
<p>Por mais que os gráficos de dispersão sejam usualmente utilizados para relacionar duas variáveis contínuas, podemos dar outras funções a eles. Em um caso exemplar, do Observatório da Insolvência da ABJ sobre Recuperações Judiciais no Estado de São Paulo, analisamos a relação entre a dívida da recuperação com a remuneração do administrador judicial. Ao apresentar a associação entre as variáveis, construímos um gráfico de dispersão. Uma forma de se encarar este gráfico é justamente pela indagação de se quanto maior a dívida total, maior a remuneração do administrador judicial. Mas, para além disso, podemos ter um outro olhar para o gráfico de dispersão. O que sabemos é que o art. 24, § 1º da lei 11.101/2005 estabelece como limite à remuneração do AJ que “o total pago ao administrador judicial não excederá 5% (cinco por cento) do valor devido aos credores submetidos à recuperação judicial ou do valor de venda dos bens na falência.” Neste caso, então, ao colocarmos uma linha de 5% em relação ao total da dívida, conseguimos observar a distância da remuneração dos AJs em relação ao máximo permitido por lei. Quando adicionamos esta camada de interpretação ao gráfico, não estamos olhando para a relação entre as variáveis (remuneração do AJ e total da dívida), mas estamos olhando para a legalidade dessa remuneração.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-obs-insolvencia" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-obs-insolvencia-1.png" class="img-fluid figure-img" width="2400"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.29: Relação entre dívida e remuneração de Administradores Judiciais: Observatório da Insolvência</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section></section><section id="gráficos-bivariados-no-tempo" class="level4" data-number="4.3.2.4"><h4 data-number="4.3.2.4" class="anchored" data-anchor-id="gráficos-bivariados-no-tempo">
<span class="header-section-number">4.3.2.4</span> Gráficos bivariados (no tempo)</h4>
<p>Chegamos, então, ao fim dos gráficos bivariados com uma variável numérica como variável de interesse. O último gráfico que nos resta observar é o caso das variáveis explicativas temporais. Esse caso é especial porque as variáveis temporais não possuem uma natureza muito definida.</p>
<p>Por exemplo, se pegarmos a variável categórica de resultado da decisão de segunda instância, ela pode assumir três valores: reformou, não reformou ou reformou parcialmente. Faria sentido, diante dessas três informações possíveis, que a gente substraísse “reformou” de “não reformou”? Obviamente não, pois não há sentido algum neste cálculo. Entretanto, se tivermos duas datas, a subtração dessas duas informações irá sim fazer sentido: ela irá nos indicar um intervalo de tempo. Com isso, já vemos que as variáveis temporais não se comportam exatamente como variáveis categóricas.</p>
<p>Agora, pensando nas variáveis numéricas contínuas, normalmente, entre um valor e outro, existem infinitos valores possíveis. Por exemplo, entre 1 e 2, existe o número 1,1 e também o 1,2. Mas entre esses valores existe o 1,11 e o 1,12. Mas entre eles, existe o 1,111 e o 1,112. E assim por diante. Essa propriedade das variáveis numéricas contínuas não está presente nas variáveis temporais. Se a variável temporal representa um ano, por exemplo, não há nada entre os anos de 2016 e 2017. Ou ainda, se a variável temporal representa datas, não há nenhum outro número entre um dia e outro.</p>
<p>Por fim, então, comparando as variáveis temporais com variáveis numéricas discretas, elas também apresentam diferenças entre si. Uma variável numérica normalmente expressa a contagem de alguma informação, por exemplo, a contagem de juízes por comarca. Esse valor é sempre positivo, inteiro e maior ou igual a zero. Se tentarmos pensar dessa forma com as variáveis temporais, o que seria uma data maior ou igual a zero? A variável igual a zero seria o dia 0/0/0000? Não faz sentido isso. Entretanto, por mais que haja algumas diferenças, a variável numérica discreta é a que mais se aproxima das variáveis temporais.</p>
<p>Por causa dessa natureza especial das variáveis temporais é que faz sentido pensarmos nos gráficos bivariados no tempo como um caso especial.</p>
<p>Antes de entrarmos na visualização gráfica dos gráficos bivariados no tempo, é importante diferenciarmos dois tipos de variáveis relacionadas a tempos. Uma coisa é uma variável que pode receber valores como “27/08/2021”; mas existe outra informação relacionada a tempo que diz respeito ao tempo transcorrido entre duas datas, por exemplo, o tempo entre a distribuição de um processo e a sua sentença. No primeiro caso, a natureza da variável é temporal (uma data); no segundo caso, a natureza da variável é uma variável numérica comum. O tipo de variável especial de que vamos tratar nesta sessão diz respeito somente ao primeiro tipo, e não ao segundo, tanto que já fizemos um gráfico com a variável “tempo”.</p>
<section id="séries-temporais" class="level5" data-number="4.3.2.4.1"><h5 data-number="4.3.2.4.1" class="anchored" data-anchor-id="séries-temporais">
<span class="header-section-number">4.3.2.4.1</span> Séries temporais</h5>
<p>O nome do gráfico que representa uma variável numérica em relação ao tempo se chama série temporal. O gráfico de uma série temporal se apresenta sempre com o tempo no eixo x e a variável numérica no eixo y.</p>
<p>Este gráfico é utilizado para “descrever apenas o comportamaneto da série”, o que vai envolver “a verificação da existência de tendências, ciclos e variações sazonais”.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>Na <a href="#fig-time-series-litig">Figura&nbsp;<span>4.30</span></a>, vemos um exemplo desse tipo de relação.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-time-series-litig" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="04-visualizacao_files/figure-html/fig-time-series-litig-1.png" class="img-fluid figure-img" width="2700"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;4.30: Série de tempo dos dados de litigiosidade.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>A figura nos mostra uma tendência se aumentar os casos em todas as regiões do Brasil a partir de 2018. Além disso, vemos que, na região Sul, entre 2015 e 2016, houve uma clara queda, no total de casos por 100 mi habitantes, em comparação com outras regiões, que ou demonstraram aumentos, ou demonstraram quedas não tão intensas.</p>
<p>O que vemos é que não estamos fazendo afirmações sobre a relação entre a variável contínua (número de casos novos por 100 mil habitantes) e a variável temporal (ano) do tipo “quanto mais tempo, mais casos”, porque não é esse tipo de relação que séries temporais nos indicam. Esse tipo de visualização está nos apontando para tendências temporais, sejam elas cíclicas, sazonais ou episódios pontuais.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography" style="display: none">
<div id="ref-ABJ2019" class="csl-entry" role="doc-biblioentry">
ABJ. 2019. <span>"<span>Avalia<span>ç</span><span>ã</span>o do Impacto de Crit<span>é</span>rios Objetivos na Distin<span>ç</span><span>ã</span>o Entre Posse para Uso e Posse para Tr<span>á</span>fico: um estudo jurim<span>é</span>trico</span>"</span>. <a href="https://abj.org.br/cases/drogas-stf/%20">https://abj.org.br/cases/drogas-stf/ </a>.
</div>
<div id="ref-ABJ2020" class="csl-entry" role="doc-biblioentry">
———. 2020. <span>"<span>O problema da cifra oculta nos tribunais brasileiros</span>"</span>. <a href="https://lab.abj.org.br/posts/2020-12-07-cifra-oculta/">https://lab.abj.org.br/posts/2020-12-07-cifra-oculta/</a>.
</div>
<div id="ref-Agresti2009" class="csl-entry" role="doc-biblioentry">
Agresti, Alan, e Barbara Finlay. 2009. <em><span>Statistical Methods for the Social Sciences</span></em>. 4.ª ed. London: Pearson.
</div>
<div id="ref-Bolfarine&amp;Bussab2005" class="csl-entry" role="doc-biblioentry">
Bolfarine, Heleno, e Wilton O. Bussab. 2005. <em><span>Elementos de Amostragem</span></em>. S<span>ã</span>o Paulo: Blucher.
</div>
<div id="ref-Bottino2015" class="csl-entry" role="doc-biblioentry">
Bottino, Thiago. 2015. <span>"<span>Panaceia universal ou rem<span>é</span>dio constitucional? Habeas corpus nos Tribunais Superiores</span>"</span>. Bras<span>í</span>lia: Ipea. <a href="http://pensando.mj.gov.br/wp-content/uploads/2015/06/thiago_55_finalizada_web.pdf">http://pensando.mj.gov.br/wp-content/uploads/2015/06/thiago_55_finalizada_web.pdf</a>.
</div>
<div id="ref-Breiman2001" class="csl-entry" role="doc-biblioentry">
Breiman, Leo. 2001. <span>"Statistical Modeling: The Two Cultures"</span>. <em>Statistical Science</em> 16 (3): 199–215.
</div>
<div id="ref-Bussab2017" class="csl-entry" role="doc-biblioentry">
Bussab, Wilton O., e Pedro A. Morettin. 2017. <em><span>Estat<span>í</span>stica B<span>á</span>sica</span></em>. 9.ª ed. S<span>ã</span>o Paulo: Saraiva.
</div>
<div id="ref-Camargo2015" class="csl-entry" role="doc-biblioentry">
Camargo, Solano de. 2015. <span>"Forum shopping: modo l<span>í</span>cito de escolha de jurisdição?"</span> Dissertação de mestrado, Universidade de São Paulo. <a href="https://doi.org/10.11606/D.2.2016.tde-21122015-193317">https://doi.org/10.11606/D.2.2016.tde-21122015-193317</a>.
</div>
<div id="ref-CCI2020" class="csl-entry" role="doc-biblioentry">
CCI, CENTER FOR COURT INNOVATION. 2020. <span>"Can Courts Be More User-Friendly? How Satisfaction Surveys Can Promote Trust and Access to Justice"</span>. <a href="https://www.courtinnovation.org/sites/default/files/media/document/2020/CCI_FactSheet_SatisfactionSurveys_04202020.pdf">https://www.courtinnovation.org/sites/default/files/media/document/2020/CCI_FactSheet_SatisfactionSurveys_04202020.pdf</a>.
</div>
<div id="ref-Cleveland1985" class="csl-entry" role="doc-biblioentry">
Cleveland, William S. 1985. <em>The Elements of Graphing Data</em>. California: Wadsworth Advanced Book Program.
</div>
<div id="ref-Epstein2014" class="csl-entry" role="doc-biblioentry">
Epstein, Lee, e Andrew D. Martin. 2014b. <em><span>An Introduction to Empirical Legal Research</span></em>. United Kingdom: Oxford University Press.
</div>
<div id="ref-Epstein&amp;Martin2014" class="csl-entry" role="doc-biblioentry">
———. 2014a. <em>An Introduction to Empirical Legal Research</em>. United Kingdom: Oxford University Press.
</div>
<div id="ref-Fulgencio2018" class="csl-entry" role="doc-biblioentry">
Fulgêncio, Henrique Augusto Figueiredo, e Alexandre Araújo Costa. 2018. <span>"<span>As fun<span>ç</span><span>õ</span>es contempor<span>â</span>neas do mandado de injun<span>ç</span><span>ã</span>o: an<span>á</span>lise emp<span>í</span>rica sobre o perfil das a<span>ç</span><span>õ</span>es ajuizadas perante o Supremo Tribunal Federal</span>"</span>. <em>Revista da Faculdade de Direito do Sul de Minas</em> 34 (2): 451–88. <a href="https://revista.fdsm.edu.br/index.php/revistafdsm/article/view/202/211">https://revista.fdsm.edu.br/index.php/revistafdsm/article/view/202/211</a>.
</div>
<div id="ref-Grinover2014" class="csl-entry" role="doc-biblioentry">
Grinover, Ada Pellegrini, ed. 2014. <span>"<span>Avalia<span>ç</span><span>ã</span>o da Presta<span>ç</span><span>ã</span>o Jurisdicional Coletiva e Individual a partir da Judicializa<span>ç</span><span>ã</span>o da Sa<span>ú</span>de</span>"</span>. CEBEPEJ.
</div>
<div id="ref-KingEtAl1994" class="csl-entry" role="doc-biblioentry">
King, Gary, Robert O Keohane, e Sidney Verba. 1994. <em><span>Designing Social Inquiry: Scientific Inference in Qualitative Research</span></em>. Princeton: Princeton University Press.
</div>
<div id="ref-Kozak2010" class="csl-entry" role="doc-biblioentry">
Kozak, Marcin. 2010. <span>"Basic principles of graphing data"</span>. <em>Sci. Agric.</em> 67 (4): 483–94.
</div>
<div id="ref-lambert2007modeling" class="csl-entry" role="doc-biblioentry">
Lambert, Paul C. 2007. <span>"Modeling of the cure fraction in survival studies"</span>. <em>The Stata Journal</em> 7 (3): 351–75.
</div>
<div id="ref-Lopes2003" class="csl-entry" role="doc-biblioentry">
Lopes, José Reinaldo de Lima. 2003. <span>"<span>A defini<span>ç</span><span>ã</span>o de interesse p<span>ú</span>blico</span>"</span>. Em <em>Processo Civil e Interesse P<span>ú</span>blico: o processo como instrumento de defesa social</em>, editado por Carlos Alberto de Salles. S<span>ã</span>o Paulo: Revista dos Tribunais.
</div>
<div id="ref-Molnar2022" class="csl-entry" role="doc-biblioentry">
Molnar, Christoph. 2022. <em>Interpretable Machine Learning: A Guide for Making Black Box Models Explainable</em>. 2.ª ed. <a href="https://christophm.github.io/interpretable-ml-book">https://christophm.github.io/interpretable-ml-book</a>.
</div>
<div id="ref-Nunes2016" class="csl-entry" role="doc-biblioentry">
Nunes, Marcelo Guedes. 2016. <em>Jurimetria: Como a Estatística Pode Reinventar o Direito</em>. São Paulo: Revista dos Tribunais.
</div>
<div id="ref-Perez2018" class="csl-entry" role="doc-biblioentry">
Perez, Marco Augusto. 2018. <span>"<span>O Controle Jurisdicional da Discricionariedade Administrativa: m<span>é</span>todos para uma jurisdi<span>ç</span><span>ã</span>o ampla das decis<span>õ</span>es administrativas</span>"</span>. Tese de livre docência, Universidade de S<span>ã</span>o Paulo.
</div>
<div id="ref-Popper1934" class="csl-entry" role="doc-biblioentry">
Popper, Karl. 1934. <em>A Lógica da Pesquisa Científica</em>. São Paulo: Cultrix.
</div>
<div id="ref-priest1984selection" class="csl-entry" role="doc-biblioentry">
Priest, George L, e Benjamin Klein. 1984. <span>"The selection of disputes for litigation"</span>. <em>The Journal of Legal Studies</em> 13 (1): 1–55.
</div>
<div id="ref-StadishEtAl2002" class="csl-entry" role="doc-biblioentry">
Shadish, William R., Thomas D. Cook, e Donald T. Campbell. s.d. <em>Experimental and quasi-experimental designs for generalized causal inference</em>. Boston: Cengage Learning.
</div>
<div id="ref-Spinney2022" class="csl-entry" role="doc-biblioentry">
Spinney, Laura. 2022. <span>"Are we witnessing the dawn of post-theory science?"</span> The Guardian. 2022. <a href="https://www.theguardian.com/technology/2022/jan/09/are-we-witnessing-the-dawn-of-post-theory-science">https://www.theguardian.com/technology/2022/jan/09/are-we-witnessing-the-dawn-of-post-theory-science</a>.
</div>
<div id="ref-SternEtAl2020" class="csl-entry" role="doc-biblioentry">
Stern, Julio Michael, Marcos Antonio Simplicio, Marcos Vinicius M. Silva, e Roberto A. Castellanos Pfeiffer. 2020. <span>"Randomization and Fair Judgment in Law and Science"</span>. arXiv. <a href="https://doi.org/10.48550/ARXIV.2008.06709">https://doi.org/10.48550/ARXIV.2008.06709</a>.
</div>
<div id="ref-Sundfeld2011" class="csl-entry" role="doc-biblioentry">
Sundfeld, Carlos Ari, Ester Gammardella Rizzi, Evorah Lusci Costa Cardoso, Flávio Beicker, Francisco Carvalho de Brito Cruz, Gabriele Estábile Bezerra, Gustavo Cesar Mazutti, et al. 2011. <em><span>Controle de constitucionalidade e judicializa<span>ç</span><span>ã</span>o: o STF frente <span>à</span> sociedade e aos Poderes</span></em>. Belo Horizonte: Faculdade de Filosofia e Ci<span>ê</span>ncias Humanas; SBPD. <a href="https://sbdp.org.br/wp/wp-content/uploads/2018/01/05-controle_de_constitucionalidade_e_judicializacao.pdf">https://sbdp.org.br/wp/wp-content/uploads/2018/01/05-controle_de_constitucionalidade_e_judicializacao.pdf</a>.
</div>
<div id="ref-Trecenti&amp;Nunes2021" class="csl-entry" role="doc-biblioentry">
Trecenti, Julio, e Marcelo Guedes Nunes. 2021. <span>"<span>Impactos da MPV 1.040/2021 no tempo de abertura de empresas</span>"</span>. <a href="https://lab.abj.org.br/posts/2021-06-11-analise-1040/">https://lab.abj.org.br/posts/2021-06-11-analise-1040/</a>.
</div>
<div id="ref-Tukey1977" class="csl-entry" role="doc-biblioentry">
Tukey, John W. 1977. <em>Exploratory Data Analysis</em>. Addison-Wesleyl Publishing Company.
</div>
<div id="ref-Whitten2015" class="csl-entry" role="doc-biblioentry">
Whitten, Paul M. Kellstedt Guy D. 2015. <em><span>Fundamentos da pesquisa em ci<span>ê</span>ncia pol<span>í</span>tica</span></em>. Sao Paulo: Blucher.
</div>
<div id="ref-Winship&amp;Mare1992" class="csl-entry" role="doc-biblioentry">
Winsihp, Christopher, e Robert D. Mare. 1992. <span>"Models for sample selection bias"</span>. <em>Annual review of sociology</em> 18 (1): 327–50.
</div>
<div id="ref-Xavier2015" class="csl-entry" role="doc-biblioentry">
Xavier, José Roberto Franco. 2015. <span>"Algumas notas teóricas sobre a pesquisa empírica em direito"</span>. <em>São Paulo Law School of Fundação Getúlio Vargas – FGV DIREITO SP, Research Paper Series – Legal Studies</em>, n. 122.
</div>
<div id="ref-xie2015" class="csl-entry" role="doc-biblioentry">
Xie, Yihui. 2015. <em>Dynamic Documents with <span>R</span> and knitr</em>. 2nd ed. Boca Raton, Florida: Chapman; Hall/CRC. <a href="http://yihui.name/knitr/">http://yihui.name/knitr/</a>.
</div>
</div>
</section></section></section></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p><span class="citation" data-cites="Cleveland1985">Cleveland (<a href="06-refs.html#ref-Cleveland1985" role="doc-biblioref">1985</a>)</span>, pp.&nbsp;9-10, tradução livre, grifos no original No original: “Graphs are exceptionally powerful tools for data analysis. The reason is nicely encapsulated in a sentence from a 1982 letter written to me by W. Edwards Deming:”Graphical methods can retain the information in the data.” Numerical data analytic procedures – such as means, standard deviations, correlation coefficients, and t-tests – are essentially data reduction techniques. Graphical methods complement such numerical techniques. Graphical methods tend to show data sets as a whole, allowing us to summarize the general behavior and to study detail. This leads to much more thorough data analysis. One reason why graphical displays can retain the information in the data is that a large amount of quantitative information can be displayed and absorbed.”<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>MORETTIN, Pedro A; TOLOI, Clélia M. C. Análise de Séries Temporais, 2a ed.&nbsp;São Paulo: Editora Blucher. 2006, p.&nbsp;3.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiada");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiada");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./03-estatisticas.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Estatísticas</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05-modelagem.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modelagem</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">Introdução à metodologia de pesquisa jurimétrica foi escrito por Ricardo Feliz Okamoto e Julio Trecenti, com apoio da <a href="https://abj.org.br">Associação Brasileira de Jurimetria (ABJ).</a></div>   
    <div class="nav-footer-right">O livro foi construído usando <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>


</body></html>